/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.67 $ of : mfd-interface.m2c,v $ 
 *
 * $Id$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/*
 * include our parent header 
 */

#include "inetNetToMediaTable_interface.h"
#include "Agent.h"
#include "AgentHandler.h"
#include "Assert.h"
#include "BabySteps.h"
#include "CacheHandler.h"
#include "CheckVarbind.h"
#include "Client.h"
#include "Debug.h"
#include "Logger.h"
#include "Logger.h"
#include "Mib.h"
#include "RowMerge.h"
#include "TableContainer.h"
#include "inetNetToMediaTable_constants.h"
#include "siglog/agent/mfd.h"

/**********************************************************************
 **********************************************************************
 ***
 *** Table inetNetToMediaTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-MIB::inetNetToMediaTable is subid 35 of ip.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.35, length: 8
 */
typedef struct inetNetToMediaTable_interface_ctx_s {

    Container_Container* container;
    Cache* cache;

    inetNetToMediaTable_registration* user_ctx;

    TableRegistrationInfo tbl_info;

    BabyStepsAccessMethods access_multiplexer;

    u_int table_dirty;

} inetNetToMediaTable_interface_ctx;

static inetNetToMediaTable_interface_ctx inetNetToMediaTable_if_ctx;

static void
_inetNetToMediaTable_container_init( inetNetToMediaTable_interface_ctx*
        if_ctx );
static void
_inetNetToMediaTable_container_shutdown( inetNetToMediaTable_interface_ctx*
        if_ctx );

Container_Container*
inetNetToMediaTable_container_get( void )
{
    return inetNetToMediaTable_if_ctx.container;
}

inetNetToMediaTable_registration*
inetNetToMediaTable_registration_get( void )
{
    return inetNetToMediaTable_if_ctx.user_ctx;
}

inetNetToMediaTable_registration*
inetNetToMediaTable_registration_set( inetNetToMediaTable_registration*
        newreg )
{
    inetNetToMediaTable_registration* old = inetNetToMediaTable_if_ctx.user_ctx;
    inetNetToMediaTable_if_ctx.user_ctx = newreg;
    return old;
}

int inetNetToMediaTable_container_size( void )
{
    return CONTAINER_SIZE( inetNetToMediaTable_if_ctx.container );
}

u_int inetNetToMediaTable_dirty_get( void )
{
    return inetNetToMediaTable_if_ctx.table_dirty;
}

void inetNetToMediaTable_dirty_set( u_int status )
{
    DEBUG_MSGTL( ( "inetNetToMediaTable:inetNetToMediaTable_dirty_set",
        "called. was %d, now %d\n",
        inetNetToMediaTable_if_ctx.table_dirty, status ) );
    inetNetToMediaTable_if_ctx.table_dirty = status;
}

/*
 * mfd multiplexer modes
 */
static NodeHandlerFT _mfd_inetNetToMediaTable_pre_request;
static NodeHandlerFT _mfd_inetNetToMediaTable_post_request;
static NodeHandlerFT _mfd_inetNetToMediaTable_object_lookup;
static NodeHandlerFT _mfd_inetNetToMediaTable_get_values;
static NodeHandlerFT _mfd_inetNetToMediaTable_check_objects;
static NodeHandlerFT _mfd_inetNetToMediaTable_undo_setup;
static NodeHandlerFT _mfd_inetNetToMediaTable_set_values;
static NodeHandlerFT _mfd_inetNetToMediaTable_undo_cleanup;
static NodeHandlerFT _mfd_inetNetToMediaTable_undo_values;
static NodeHandlerFT _mfd_inetNetToMediaTable_commit;
static NodeHandlerFT _mfd_inetNetToMediaTable_undo_commit;
static NodeHandlerFT _mfd_inetNetToMediaTable_irreversible_commit;
static NodeHandlerFT _mfd_inetNetToMediaTable_check_dependencies;

static inline int
_inetNetToMediaTable_undo_column( inetNetToMediaTable_rowreq_ctx*
                                      rowreq_ctx,
    Types_VariableList*
        var,
    int column );

static inline int
_inetNetToMediaTable_check_indexes( inetNetToMediaTable_rowreq_ctx*
        rowreq_ctx );

/**
 * @internal
 * Initialize the table inetNetToMediaTable 
 *    (Define its contents and how it's structured)
 */
void _inetNetToMediaTable_initialize_interface( inetNetToMediaTable_registration* reg_ptr, u_long flags )
{
    BabyStepsAccessMethods* access_multiplexer = &inetNetToMediaTable_if_ctx.access_multiplexer;
    TableRegistrationInfo* tbl_info = &inetNetToMediaTable_if_ctx.tbl_info;
    HandlerRegistration* reginfo;
    MibHandler* handler;
    int mfd_modes = 0;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_initialize_interface", "called\n" ) );

    /*************************************************
     *
     * save interface context for inetNetToMediaTable
     */
    /*
     * Setting up the table's definition
     */
    Table_helperAddIndexes( tbl_info, ASN01_INTEGER,
        /** index: inetNetToMediaIfIndex */
        ASN01_INTEGER,
        /** index: inetNetToMediaNetAddressType */
        ASN01_OCTET_STR,
        /** index: inetNetToMediaNetAddress */
        0 );

    /*
     * Define the minimum and maximum accessible columns.  This
     * optimizes retrieval. 
     */
    tbl_info->min_column = INETNETTOMEDIATABLE_MIN_COL;
    tbl_info->max_column = INETNETTOMEDIATABLE_MAX_COL;

    /*
     * save users context
     */
    inetNetToMediaTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    inetNetToMediaTable_init_data( reg_ptr );

    /*
     * set up the container
     */
    _inetNetToMediaTable_container_init( &inetNetToMediaTable_if_ctx );
    if ( NULL == inetNetToMediaTable_if_ctx.container ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "could not initialize container for inetNetToMediaTable\n" );
        return;
    }

    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_inetNetToMediaTable_object_lookup;
    access_multiplexer->get_values = _mfd_inetNetToMediaTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_inetNetToMediaTable_pre_request;
    access_multiplexer->post_request = _mfd_inetNetToMediaTable_post_request;

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_inetNetToMediaTable_check_objects;
    access_multiplexer->undo_setup = _mfd_inetNetToMediaTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_inetNetToMediaTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_inetNetToMediaTable_set_values;
    access_multiplexer->undo_sets = _mfd_inetNetToMediaTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_inetNetToMediaTable_commit;
    access_multiplexer->undo_commit = _mfd_inetNetToMediaTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_inetNetToMediaTable_irreversible_commit;

    /*
     * REQUIRED for tables with dependencies
     */
    access_multiplexer->consistency_checks = _mfd_inetNetToMediaTable_check_dependencies;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUG_MSGTL( ( "inetNetToMediaTable:init_inetNetToMediaTable",
        "Registering inetNetToMediaTable as a mibs-for-dummies table.\n" ) );
    handler = BabySteps_accessMultiplexerGet( access_multiplexer );
    reginfo = AgentHandler_registrationCreate( "inetNetToMediaTable", handler,
        inetNetToMediaTable_oid,
        inetNetToMediaTable_oid_size,
        HANDLER_CAN_BABY_STEP
            | HANDLER_CAN_RWRITE );
    if ( NULL == reginfo ) {
        Logger_log( LOGGER_PRIORITY_ERR, "error registering table inetNetToMediaTable\n" );
        return;
    }
    reginfo->my_reg_void = &inetNetToMediaTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if ( access_multiplexer->object_lookup )
        mfd_modes |= BabyStepsMode_OBJECT_LOOKUP;
    if ( access_multiplexer->pre_request )
        mfd_modes |= BabyStepsMode_PRE_REQUEST;
    if ( access_multiplexer->post_request )
        mfd_modes |= BabyStepsMode_POST_REQUEST;

    if ( access_multiplexer->set_values )
        mfd_modes |= BabyStepsMode_SET_VALUES;
    if ( access_multiplexer->irreversible_commit )
        mfd_modes |= BabyStepsMode_IRREVERSIBLE_COMMIT;
    if ( access_multiplexer->object_syntax_checks )
        mfd_modes |= BabyStepsMode_CHECK_OBJECT;

    if ( access_multiplexer->undo_setup )
        mfd_modes |= BabyStepsMode_UNDO_SETUP;
    if ( access_multiplexer->undo_cleanup )
        mfd_modes |= BabyStepsMode_UNDO_CLEANUP;
    if ( access_multiplexer->undo_sets )
        mfd_modes |= BabyStepsMode_UNDO_SETS;

    if ( access_multiplexer->row_creation )
        mfd_modes |= BabyStepsMode_ROW_CREATE;
    if ( access_multiplexer->consistency_checks )
        mfd_modes |= BabyStepsMode_CHECK_CONSISTENCY;
    if ( access_multiplexer->commit )
        mfd_modes |= BabyStepsMode_COMMIT;
    if ( access_multiplexer->undo_commit )
        mfd_modes |= BabyStepsMode_UNDO_COMMIT;

    handler = BabySteps_handlerGet( mfd_modes );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = RowMerge_getRowMergeHandler( reginfo->rootoid_len + 2 );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject container_table helper
     */
    handler = TableContainer_handlerGet( tbl_info,
        inetNetToMediaTable_if_ctx.container,
        TABLE_CONTAINER_KEY_NETSNMP_INDEX );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if ( NULL != inetNetToMediaTable_if_ctx.cache ) {
        handler = CacheHandler_handlerGet( inetNetToMediaTable_if_ctx.cache );
        AgentHandler_injectHandler( reginfo, handler );
    }

    /*
     * register table
     */
    Table_registerTable( reginfo, tbl_info );

} /* _inetNetToMediaTable_initialize_interface */

/**
 * @internal
 * Shutdown the table inetNetToMediaTable
 */
void _inetNetToMediaTable_shutdown_interface( inetNetToMediaTable_registration*
        reg_ptr )
{
    /*
     * shutdown the container
     */
    _inetNetToMediaTable_container_shutdown( &inetNetToMediaTable_if_ctx );
}

void inetNetToMediaTable_valid_columns_set( ColumnInfo* vc )
{
    inetNetToMediaTable_if_ctx.tbl_info.valid_columns = vc;
} /* inetNetToMediaTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int inetNetToMediaTable_index_to_oid( Types_Index* oid_idx,
    inetNetToMediaTable_mib_index* mib_idx )
{
    int err = PRIOT_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * inetNetToMediaIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    Types_VariableList var_inetNetToMediaIfIndex;
    /*
     * inetNetToMediaNetAddressType(2)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    Types_VariableList var_inetNetToMediaNetAddressType;
    /*
     * inetNetToMediaNetAddress(3)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    Types_VariableList var_inetNetToMediaNetAddress;

    /*
     * set up varbinds
     */
    memset( &var_inetNetToMediaIfIndex, 0x00,
        sizeof( var_inetNetToMediaIfIndex ) );
    var_inetNetToMediaIfIndex.type = ASN01_INTEGER;
    memset( &var_inetNetToMediaNetAddressType, 0x00,
        sizeof( var_inetNetToMediaNetAddressType ) );
    var_inetNetToMediaNetAddressType.type = ASN01_INTEGER;
    memset( &var_inetNetToMediaNetAddress, 0x00,
        sizeof( var_inetNetToMediaNetAddress ) );
    var_inetNetToMediaNetAddress.type = ASN01_OCTET_STR;

    /*
     * chain temp index varbinds together
     */
    var_inetNetToMediaIfIndex.nextVariable = &var_inetNetToMediaNetAddressType;
    var_inetNetToMediaNetAddressType.nextVariable = &var_inetNetToMediaNetAddress;
    var_inetNetToMediaNetAddress.nextVariable = NULL;

    DEBUG_MSGTL( ( "verbose:inetNetToMediaTable:inetNetToMediaTable_index_to_oid", "called\n" ) );

    /*
     * inetNetToMediaIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H 
     */
    Client_setVarValue( &var_inetNetToMediaIfIndex,
        ( u_char* )&mib_idx->inetNetToMediaIfIndex,
        sizeof( mib_idx->inetNetToMediaIfIndex ) );

    /*
     * inetNetToMediaNetAddressType(2)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    Client_setVarValue( &var_inetNetToMediaNetAddressType,
        ( u_char* )&mib_idx->inetNetToMediaNetAddressType,
        sizeof( mib_idx->inetNetToMediaNetAddressType ) );

    /*
     * inetNetToMediaNetAddress(3)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    Client_setVarValue( &var_inetNetToMediaNetAddress,
        ( u_char* )&mib_idx->inetNetToMediaNetAddress,
        mib_idx->inetNetToMediaNetAddress_len * sizeof( mib_idx->inetNetToMediaNetAddress[ 0 ] ) );

    err = Mib_buildOidNoalloc( oid_idx->oids, oid_idx->len, &oid_idx->len,
        NULL, 0, &var_inetNetToMediaIfIndex );
    if ( err )
        Logger_log( LOGGER_PRIORITY_ERR, "error %d converting index to oid\n", err );

    /*
     * parsing may have allocated memory. free it.
     */
    Client_resetVarBuffers( &var_inetNetToMediaIfIndex );

    return err;
} /* inetNetToMediaTable_index_to_oid */

/**
 * extract inetNetToMediaTable indexes from a Types_Index
 *
 * @retval PRIOT_ERR_NOERROR  : no error
 * @retval PRIOT_ERR_GENERR   : error
 */
int inetNetToMediaTable_index_from_oid( Types_Index* oid_idx,
    inetNetToMediaTable_mib_index* mib_idx )
{
    int err = PRIOT_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * inetNetToMediaIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H
     */
    Types_VariableList var_inetNetToMediaIfIndex;
    /*
     * inetNetToMediaNetAddressType(2)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    Types_VariableList var_inetNetToMediaNetAddressType;
    /*
     * inetNetToMediaNetAddress(3)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    Types_VariableList var_inetNetToMediaNetAddress;

    /*
     * set up varbinds
     */
    memset( &var_inetNetToMediaIfIndex, 0x00,
        sizeof( var_inetNetToMediaIfIndex ) );
    var_inetNetToMediaIfIndex.type = ASN01_INTEGER;
    memset( &var_inetNetToMediaNetAddressType, 0x00,
        sizeof( var_inetNetToMediaNetAddressType ) );
    var_inetNetToMediaNetAddressType.type = ASN01_INTEGER;
    memset( &var_inetNetToMediaNetAddress, 0x00,
        sizeof( var_inetNetToMediaNetAddress ) );
    var_inetNetToMediaNetAddress.type = ASN01_OCTET_STR;

    /*
     * chain temp index varbinds together
     */
    var_inetNetToMediaIfIndex.nextVariable = &var_inetNetToMediaNetAddressType;
    var_inetNetToMediaNetAddressType.nextVariable = &var_inetNetToMediaNetAddress;
    var_inetNetToMediaNetAddress.nextVariable = NULL;

    DEBUG_MSGTL( ( "verbose:inetNetToMediaTable:inetNetToMediaTable_index_from_oid", "called\n" ) );

    /*
     * parse the oid into the individual index components
     */
    err = Mib_parseOidIndexes( oid_idx->oids, oid_idx->len,
        &var_inetNetToMediaIfIndex );
    if ( err == PRIOT_ERR_NOERROR ) {
        /*
         * copy out values
         */
        mib_idx->inetNetToMediaIfIndex = *( ( long* )var_inetNetToMediaIfIndex.val.string );
        mib_idx->inetNetToMediaNetAddressType = *( ( u_long* )var_inetNetToMediaNetAddressType.val.string );
        /*
         * NOTE: val_len is in bytes, inetNetToMediaNetAddress_len might not be
         */
        if ( var_inetNetToMediaNetAddress.valLen > sizeof( mib_idx->inetNetToMediaNetAddress ) )
            err = PRIOT_ERR_GENERR;
        else {
            memcpy( mib_idx->inetNetToMediaNetAddress,
                var_inetNetToMediaNetAddress.val.string,
                var_inetNetToMediaNetAddress.valLen );
            mib_idx->inetNetToMediaNetAddress_len = var_inetNetToMediaNetAddress.valLen / sizeof( mib_idx->inetNetToMediaNetAddress[ 0 ] );
        }
    }

    /*
     * parsing may have allocated memory. free it.
     */
    Client_resetVarBuffers( &var_inetNetToMediaIfIndex );

    return err;
} /* inetNetToMediaTable_index_from_oid */

/*
 *********************************************************************
 * @internal
 * allocate resources for a inetNetToMediaTable_rowreq_ctx
 */
inetNetToMediaTable_rowreq_ctx*
inetNetToMediaTable_allocate_rowreq_ctx( inetNetToMediaTable_data* data,
    void* user_init_ctx )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = TOOLS_MALLOC_TYPEDEF( inetNetToMediaTable_rowreq_ctx );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:inetNetToMediaTable_allocate_rowreq_ctx", "called\n" ) );

    if ( NULL == rowreq_ctx ) {
        Logger_log( LOGGER_PRIORITY_ERR, "Couldn't allocate memory for a "
                                         "inetNetToMediaTable_rowreq_ctx.\n" );
        return NULL;
    } else {
        if ( NULL != data ) {
            /*
             * track if we got data from user
             */
            rowreq_ctx->rowreq_flags |= MFD_ROW_DATA_FROM_USER;
            rowreq_ctx->data = data;
        } else if ( NULL == ( rowreq_ctx->data = inetNetToMediaTable_allocate_data() ) ) {
            TOOLS_FREE( rowreq_ctx );
            return NULL;
        }
    }

    /*
     * undo context will be allocated when needed (in *_undo_setup)
     */

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->inetNetToMediaTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if ( !( rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER ) ) {
        if ( ErrorCode_SUCCESS != inetNetToMediaTable_rowreq_ctx_init( rowreq_ctx,
                                      user_init_ctx ) ) {
            inetNetToMediaTable_release_rowreq_ctx( rowreq_ctx );
            rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* inetNetToMediaTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a inetNetToMediaTable_rowreq_ctx
 */
void inetNetToMediaTable_release_rowreq_ctx( inetNetToMediaTable_rowreq_ctx*
        rowreq_ctx )
{
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:inetNetToMediaTable_release_rowreq_ctx", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    inetNetToMediaTable_rowreq_ctx_cleanup( rowreq_ctx );

    /*
     * for non-transient data, don't free data we got from the user
     */
    if ( ( rowreq_ctx->data ) && !( rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER ) )
        inetNetToMediaTable_release_data( rowreq_ctx->data );

    if ( rowreq_ctx->undo )
        inetNetToMediaTable_release_data( rowreq_ctx->undo );

    /*
     * free index oid pointer
     */
    if ( rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp )
        free( rowreq_ctx->oid_idx.oids );

    TOOLS_FREE( rowreq_ctx );
} /* inetNetToMediaTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetNetToMediaTable_pre_request( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_pre_request", "called\n" ) );

    if ( 1 != RowMerge_statusFirst( reginfo, agtreq_info ) ) {
        DEBUG_MSGTL( ( "internal:inetNetToMediaTable",
            "skipping additional pre_request\n" ) );
        return PRIOT_ERR_NOERROR;
    }

    rc = inetNetToMediaTable_pre_request( inetNetToMediaTable_if_ctx.user_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetNetToMediaTable", "error %d from "
                                              "inetNetToMediaTable_pre_request\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetNetToMediaTable_post_request( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    int rc, packet_rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_post_request", "called\n" ) );

    /*
     * release row context, if deleted
     */
    if ( rowreq_ctx && ( rowreq_ctx->rowreq_flags & MFD_ROW_DELETED ) )
        inetNetToMediaTable_release_rowreq_ctx( rowreq_ctx );

    /*
     * wait for last call before calling user
     */
    if ( 1 != RowMerge_statusLast( reginfo, agtreq_info ) ) {
        DEBUG_MSGTL( ( "internal:inetNetToMediaTable",
            "waiting for last post_request\n" ) );
        return PRIOT_ERR_NOERROR;
    }

    packet_rc = Agent_checkAllRequestsError( agtreq_info->asp, 0 );
    if ( ( MFD_SUCCESS != packet_rc ) && inetNetToMediaTable_dirty_get() ) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        Logger_log( LOGGER_PRIORITY_WARNING,
            "inetNetToMediaTable dirty flag set in post_request "
            "but status != SUCCESS.\n" );
    }

    rc = inetNetToMediaTable_post_request( inetNetToMediaTable_if_ctx.user_ctx, packet_rc );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetNetToMediaTable", "error %d from "
                                              "inetNetToMediaTable_post_request\n",
            rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_post_request */

/**
 * @internal
 * wrapper
 */
static inetNetToMediaTable_rowreq_ctx*
_mfd_inetNetToMediaTable_rowreq_from_index( Types_Index* oid_idx,
    int* rc_ptr )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx;
    inetNetToMediaTable_mib_index mib_idx;
    int rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_rowreq_from_index", "called\n" ) );

    if ( NULL == rc_ptr )
        rc_ptr = &rc;
    *rc_ptr = MFD_SUCCESS;

    memset( &mib_idx, 0x0, sizeof( mib_idx ) );

    /*
     * try to parse oid
     */
    *rc_ptr = inetNetToMediaTable_index_from_oid( oid_idx, &mib_idx );
    if ( MFD_SUCCESS != *rc_ptr ) {
        DEBUG_MSGT( ( "inetNetToMediaTable", "error parsing index\n" ) );
        return NULL;
    }

    /*
     * allocate new context
     */
    rowreq_ctx = inetNetToMediaTable_allocate_rowreq_ctx( NULL, NULL );
    if ( NULL == rowreq_ctx ) {
        *rc_ptr = MFD_ERROR;
        return NULL; /* msg already logged */
    }

    memcpy( &rowreq_ctx->tbl_idx, &mib_idx, sizeof( mib_idx ) );

    /*
     * check indexes
     */
    *rc_ptr = _inetNetToMediaTable_check_indexes( rowreq_ctx );
    if ( MFD_SUCCESS != *rc_ptr ) {
        Assert_assert( ( *rc_ptr == PRIOT_ERR_NOCREATION ) || ( *rc_ptr == PRIOT_ERR_INCONSISTENTNAME ) );
        inetNetToMediaTable_release_rowreq_ctx( rowreq_ctx );
        return NULL;
    }

    /*
     * copy indexes
     */
    rowreq_ctx->oid_idx.len = oid_idx->len;
    memcpy( rowreq_ctx->oid_idx.oids, oid_idx->oids,
        oid_idx->len * sizeof( oid ) );

    return rowreq_ctx;
} /* _mfd_inetNetToMediaTable_rowreq_from_index */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetNetToMediaTable_object_lookup( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc = PRIOT_ERR_NOERROR;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_object_lookup", "called\n" ) );

    /*
     * get our context from mfd
     * inetNetToMediaTable_interface_ctx *if_ctx =
     *             (inetNetToMediaTable_interface_ctx *)reginfo->my_reg_void;
     */

    if ( NULL == rowreq_ctx ) {
        TableRequestInfo* tblreq_info;
        Types_Index oid_idx;

        tblreq_info = Table_extractTableInfo( requests );
        if ( NULL == tblreq_info ) {
            Logger_log( LOGGER_PRIORITY_ERR, "request had no table info\n" );
            return MFD_ERROR;
        }

        /*
         * try create rowreq
         */
        oid_idx.oids = tblreq_info->index_oid;
        oid_idx.len = tblreq_info->index_oid_len;

        rowreq_ctx = _mfd_inetNetToMediaTable_rowreq_from_index( &oid_idx, &rc );
        if ( MFD_SUCCESS == rc ) {
            Assert_assert( NULL != rowreq_ctx );
            rowreq_ctx->rowreq_flags |= MFD_ROW_CREATED;
            /*
             * add rowreq_ctx to request data lists
             */
            TableContainer_rowInsert( requests, ( Types_Index* )
                                                    rowreq_ctx );
        }
    }

    if ( MFD_SUCCESS != rc )
        Agent_requestSetErrorAll( requests, rc );
    else
        inetNetToMediaTable_row_prep( rowreq_ctx );

    return PRIOT_VALIDATE_ERR( rc );
} /* _mfd_inetNetToMediaTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
static inline int
_inetNetToMediaTable_get_column( inetNetToMediaTable_rowreq_ctx*
                                     rowreq_ctx,
    Types_VariableList* var,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_get_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetNetToMediaPhysAddress(4)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAPHYSADDRESS:
        var->type = ASN01_OCTET_STR;
        rc = inetNetToMediaPhysAddress_get( rowreq_ctx,
            ( char** )&var->val.string,
            &var->valLen );
        break;

    /*
         * inetNetToMediaLastUpdated(5)/TimeStamp/ASN_TIMETICKS/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_INETNETTOMEDIALASTUPDATED:
        var->valLen = sizeof( u_long );
        var->type = ASN01_TIMETICKS;
        rc = inetNetToMediaLastUpdated_get( rowreq_ctx,
            ( u_long* )var->val.string );
        break;

    /*
         * inetNetToMediaType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h 
         */
    case COLUMN_INETNETTOMEDIATYPE:
        var->valLen = sizeof( u_long );
        var->type = ASN01_INTEGER;
        rc = inetNetToMediaType_get( rowreq_ctx,
            ( u_long* )var->val.string );
        break;

    /*
         * inetNetToMediaState(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIASTATE:
        var->valLen = sizeof( u_long );
        var->type = ASN01_INTEGER;
        rc = inetNetToMediaState_get( rowreq_ctx,
            ( u_long* )var->val.string );
        break;

    /*
         * inetNetToMediaRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIAROWSTATUS:
        var->valLen = sizeof( u_long );
        var->type = ASN01_INTEGER;
        rc = inetNetToMediaRowStatus_get( rowreq_ctx,
            ( u_long* )var->val.string );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetNetToMediaTable_get_column\n",
            column );
        break;
    }

    return rc;
} /* _inetNetToMediaTable_get_column */

int _mfd_inetNetToMediaTable_get_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    u_char* old_string;
    void ( *dataFreeHook )( void* );
    int rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_get_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    for ( ; requests; requests = requests->next ) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->val.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if ( NULL == requests->requestvb->val.string ) {
            requests->requestvb->val.string = requests->requestvb->buf;
            requests->requestvb->valLen = sizeof( requests->requestvb->buf );
        } else if ( requests->requestvb->buf == requests->requestvb->val.string ) {
            if ( requests->requestvb->valLen != sizeof( requests->requestvb->buf ) )
                requests->requestvb->valLen = sizeof( requests->requestvb->buf );
        }

        /*
         * get column data
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetNetToMediaTable_get_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( rc ) {
            if ( MFD_SKIP == rc ) {
                requests->requestvb->type = PRIOT_NOSUCHINSTANCE;
                rc = PRIOT_ERR_NOERROR;
            }
        } else if ( NULL == requests->requestvb->val.string ) {
            Logger_log( LOGGER_PRIORITY_ERR, "NULL varbind data pointer!\n" );
            rc = PRIOT_ERR_GENERR;
        }
        if ( rc )
            Agent_requestSetError( requests, PRIOT_VALIDATE_ERR( rc ) );

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if ( old_string && ( old_string != requests->requestvb->buf ) && ( requests->requestvb->val.string != old_string ) ) {
            if ( dataFreeHook )
                ( *dataFreeHook )( old_string );
            else
                free( old_string );
        }
    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_get_values */

static inline int
_inetNetToMediaTable_check_indexes( inetNetToMediaTable_rowreq_ctx*
        rowreq_ctx )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_check_indexes", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * (INDEX) inetNetToMediaIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H 
     */
    /*
     * check defined range(s). 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( ( rowreq_ctx->tbl_idx.inetNetToMediaIfIndex < 1 )
               || ( rowreq_ctx->tbl_idx.inetNetToMediaIfIndex > 2147483647 ) ) ) {
        rc = PRIOT_ERR_WRONGVALUE;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetNetToMediaIfIndex_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetNetToMediaNetAddressType(2)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    /*
     * check that the value is one of defined enums 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_UNKNOWN )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_IPV4 )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_IPV6 )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_IPV4Z )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_IPV6Z )
        && ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddressType != INETADDRESSTYPE_DNS ) ) {
        rc = PRIOT_ERR_WRONGVALUE;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetNetToMediaNetAddressType_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetNetToMediaNetAddress(3)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    /*
     * check defined range(s). 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddress_len < 0 )
               || ( rowreq_ctx->tbl_idx.inetNetToMediaNetAddress_len > 255 ) ) ) {
        rc = PRIOT_ERR_WRONGLENGTH;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetNetToMediaNetAddress_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * if individual parts look ok, check them as a whole
     */
    return inetNetToMediaTable_validate_index( inetNetToMediaTable_if_ctx.user_ctx, rowreq_ctx );
} /* _inetNetToMediaTable_check_indexes */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
static inline int
_inetNetToMediaTable_check_column( inetNetToMediaTable_rowreq_ctx*
                                       rowreq_ctx,
    Types_VariableList* var,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_check_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {
    /*
         * (INDEX) inetNetToMediaIfIndex(1)/InterfaceIndex/ASN_INTEGER/long(long)//l/a/w/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAIFINDEX:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetNetToMediaNetAddressType(2)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIANETADDRESSTYPE:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetNetToMediaNetAddress(3)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
         */
    case COLUMN_INETNETTOMEDIANETADDRESS:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /*
         * inetNetToMediaPhysAddress(4)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAPHYSADDRESS:
        rc = CheckVarbind_type( var, ASN01_OCTET_STR );
        /*
         * check defined range(s). 
         */
        if ( ( ErrorCode_SUCCESS == rc )
            && ( ( var->valLen < 0 ) || ( var->valLen > 65535 ) ) ) {
            rc = PRIOT_ERR_WRONGLENGTH;
        }
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetNetToMediaTable:_inetNetToMediaTable_check_column:inetNetToMediaPhysAddress", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetNetToMediaPhysAddress_check_value( rowreq_ctx,
                ( char* )var->val.string,
                var->valLen );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetNetToMediaPhysAddress_check_value\n",
                    rc );
                rc = PRIOT_ERR_GENERR;
            }
        }
        break;

    /*
         * inetNetToMediaLastUpdated(5)/TimeStamp/ASN_TIMETICKS/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_INETNETTOMEDIALASTUPDATED:
        rc = PRIOT_ERR_NOTWRITABLE;
        break;

    /*
         * inetNetToMediaType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h 
         */
    case COLUMN_INETNETTOMEDIATYPE:
        rc = CheckVarbind_type( var, ASN01_INTEGER );
        /*
         * check that the value is one of defined enums 
         */
        if ( ( ErrorCode_SUCCESS == rc )
            && ( *var->val.integer != INETNETTOMEDIATYPE_OTHER )
            && ( *var->val.integer != INETNETTOMEDIATYPE_INVALID )
            && ( *var->val.integer != INETNETTOMEDIATYPE_DYNAMIC )
            && ( *var->val.integer != INETNETTOMEDIATYPE_STATIC )
            && ( *var->val.integer != INETNETTOMEDIATYPE_LOCAL ) ) {
            rc = PRIOT_ERR_WRONGVALUE;
        }
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetNetToMediaTable:_inetNetToMediaTable_check_column:inetNetToMediaType", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetNetToMediaType_check_value( rowreq_ctx,
                *( ( u_long* )var->val.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetNetToMediaType_check_value\n",
                    rc );
                rc = PRIOT_ERR_GENERR;
            }
        }
        break;

    /*
         * inetNetToMediaState(7)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIASTATE:
        rc = PRIOT_ERR_NOTWRITABLE;
        break;

    /*
         * inetNetToMediaRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIAROWSTATUS:
        rc = CheckVarbind_rowStatusValue( var );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetNetToMediaTable:_inetNetToMediaTable_check_column:inetNetToMediaRowStatus", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetNetToMediaRowStatus_check_value( rowreq_ctx,
                *( ( u_long* )var->val.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetNetToMediaRowStatus_check_value\n",
                    rc );
                rc = PRIOT_ERR_GENERR;
            }
        }
        break;

    default: /** We shouldn't get here */
        rc = PRIOT_ERR_GENERR;
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetNetToMediaTable_check_column\n",
            column );
    }

    return rc;
} /* _inetNetToMediaTable_check_column */

int _mfd_inetNetToMediaTable_check_objects( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    int rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_check_objects", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    for ( ; requests; requests = requests->next ) {

        /*
         * get column number from table request info, and check that column
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetNetToMediaTable_check_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( rc ) {
            Agent_requestSetError( requests, PRIOT_VALIDATE_ERR( rc ) );
            break;
        }

    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_check_objects */

/*----------------------------------------------------------------------
 *
 * SET: check dependencies
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check dependencies wrapper
 */
static int
_mfd_inetNetToMediaTable_check_dependencies( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_check_dependencies", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetNetToMediaTable_check_dependencies( rowreq_ctx );
    if ( rc ) {
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_check_dependencies\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_check_dependencies */

/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
static inline int
_inetNetToMediaTable_undo_setup_column( inetNetToMediaTable_rowreq_ctx*
                                            rowreq_ctx,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_undo_setup_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetNetToMediaPhysAddress(4)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAPHYSADDRESS:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIAPHYSADDRESS_FLAG;
        rc = inetNetToMediaPhysAddress_undo_setup( rowreq_ctx );
        break;

    /*
         * inetNetToMediaType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h 
         */
    case COLUMN_INETNETTOMEDIATYPE:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIATYPE_FLAG;
        rc = inetNetToMediaType_undo_setup( rowreq_ctx );
        break;

    /*
         * inetNetToMediaRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIAROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIAROWSTATUS_FLAG;
        rc = inetNetToMediaRowStatus_undo_setup( rowreq_ctx );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetNetToMediaTable_undo_setup_column\n",
            column );
        break;
    }

    return rc;
} /* _inetNetToMediaTable_undo_setup_column */

/**
 * @internal
 * undo setup
 */
int _mfd_inetNetToMediaTable_undo_setup( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_undo_setup", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = inetNetToMediaTable_allocate_data();
    if ( NULL == rowreq_ctx->undo ) {
        /** msg already logged */
        Agent_requestSetErrorAll( requests,
            PRIOT_ERR_RESOURCEUNAVAILABLE );
        return PRIOT_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = inetNetToMediaTable_undo_setup( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_undo_setup\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    } else {
        /*
         * column undo setup
         */
        TableRequestInfo* tri;
        for ( ; requests; requests = requests->next ) {
            /*
             * set column data
             */
            tri = Table_extractTableInfo( requests );
            if ( NULL == tri )
                continue;

            rc = _inetNetToMediaTable_undo_setup_column( rowreq_ctx,
                tri->colnum );
            if ( MFD_SUCCESS != rc ) {
                DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                          "inetNetToMediaTable_undo_setup_column\n",
                    rc ) );
                Agent_setRequestError( agtreq_info, requests,
                    PRIOT_VALIDATE_ERR( rc ) );
            }
        } /* for results */
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int _mfd_inetNetToMediaTable_undo_cleanup( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    int rc;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_undo_cleanup", "called\n" ) );

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if ( NULL == rowreq_ctx )
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = inetNetToMediaTable_undo_cleanup( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_undo_cleanup\n",
            rc ) );
    }

    /*
     * release undo context, if needed
     */
    if ( rowreq_ctx->undo ) {
        inetNetToMediaTable_release_data( rowreq_ctx->undo );
        rowreq_ctx->undo = NULL;
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
static inline int
_inetNetToMediaTable_set_column( inetNetToMediaTable_rowreq_ctx*
                                     rowreq_ctx,
    Types_VariableList* var,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_set_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetNetToMediaPhysAddress(4)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAPHYSADDRESS:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIAPHYSADDRESS_FLAG;
        rc = inetNetToMediaPhysAddress_set( rowreq_ctx,
            ( char* )var->val.string,
            var->valLen );
        break;

    /*
         * inetNetToMediaType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h 
         */
    case COLUMN_INETNETTOMEDIATYPE:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIATYPE_FLAG;
        rc = inetNetToMediaType_set( rowreq_ctx,
            *( ( u_long* )var->val.string ) );
        break;

    /*
         * inetNetToMediaRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIAROWSTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_INETNETTOMEDIAROWSTATUS_FLAG;
        rc = inetNetToMediaRowStatus_set( rowreq_ctx,
            *( ( u_long* )var->val.string ) );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetNetToMediaTable_set_column\n",
            column );
        rc = PRIOT_ERR_GENERR;
        break;
    }

    return rc;
} /* _inetNetToMediaTable_set_column */

int _mfd_inetNetToMediaTable_set_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    int rc = PRIOT_ERR_NOERROR;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_set_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rowreq_ctx->column_set_flags = 0;
    for ( ; requests; requests = requests->next ) {
        /*
         * set column data
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetNetToMediaTable_set_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( MFD_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                      "inetNetToMediaTable_set_column\n",
                rc ) );
            Agent_setRequestError( agtreq_info, requests,
                PRIOT_VALIDATE_ERR( rc ) );
        }
    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int _mfd_inetNetToMediaTable_commit( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetNetToMediaTable_commit( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_commit\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        inetNetToMediaTable_dirty_set( inetNetToMediaTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return PRIOT_ERR_NOERROR;
}

int _mfd_inetNetToMediaTable_undo_commit( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_undo_commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        u_int d = inetNetToMediaTable_dirty_get();

        Assert_assert( d != 0 );
        if ( d )
            inetNetToMediaTable_dirty_set( d - 1 );
    }

    rc = inetNetToMediaTable_undo_commit( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_undo_commit\n",
            rc ) );
    }

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        Logger_log( LOGGER_PRIORITY_WARNING,
            "inetNetToMediaTable row dirty flag still set after undo_commit\n" );
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * undo the value for a particular column
 */
static inline int
_inetNetToMediaTable_undo_column( inetNetToMediaTable_rowreq_ctx*
                                      rowreq_ctx,
    Types_VariableList* var,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_undo_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetNetToMediaPhysAddress(4)/PhysAddress/ASN_OCTET_STR/char(char)//L/A/W/e/R/d/H 
         */
    case COLUMN_INETNETTOMEDIAPHYSADDRESS:
        rc = inetNetToMediaPhysAddress_undo( rowreq_ctx );
        break;

    /*
         * inetNetToMediaType(6)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/D/h 
         */
    case COLUMN_INETNETTOMEDIATYPE:
        rc = inetNetToMediaType_undo( rowreq_ctx );
        break;

    /*
         * inetNetToMediaRowStatus(8)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETNETTOMEDIAROWSTATUS:
        rc = inetNetToMediaRowStatus_undo( rowreq_ctx );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetNetToMediaTable_undo_column\n",
            column );
        break;
    }

    return rc;
} /* _inetNetToMediaTable_undo_column */

int _mfd_inetNetToMediaTable_undo_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_undo_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetNetToMediaTable_undo( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                  "inetNetToMediaTable_undo\n",
            rc ) );
    }

    for ( ; requests; requests = requests->next ) {
        /*
         * set column data
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetNetToMediaTable_undo_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( MFD_SUCCESS != rc ) {
            /*
             * nothing we can do about it but log it
             */
            DEBUG_MSGTL( ( "inetNetToMediaTable:mfd", "error %d from "
                                                      "inetNetToMediaTable_undo_column\n",
                rc ) );
        }
    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int _mfd_inetNetToMediaTable_irreversible_commit( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info, RequestInfo* requests )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_mfd_inetNetToMediaTable_irreversible:commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DELETED ) {
        if ( !( rowreq_ctx->rowreq_flags & MFD_ROW_CREATED ) )
            CONTAINER_REMOVE( inetNetToMediaTable_if_ctx.container, rowreq_ctx );
    } else {
        if ( rowreq_ctx->column_set_flags ) {
            rowreq_ctx->column_set_flags = 0;
        }
        if ( rowreq_ctx->rowreq_flags & MFD_ROW_CREATED ) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT( inetNetToMediaTable_if_ctx.container,
                rowreq_ctx );
        }
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetNetToMediaTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free( Container_Container* container );

/**
 * @internal
 */
static int
_cache_load( Cache* cache, void* vmagic )
{
    DEBUG_TRACE;

    if ( ( NULL == cache ) || ( NULL == cache->magic ) ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid cache for inetNetToMediaTable_cache_load\n" );
        return -1;
    }
    DEBUG_MSGTL( ( "inetNetToMediaTable/cache", "inetNetToMedia_load %p/%p\n",
        cache, cache->magic ) );

    Assert_assert( ( 0 == cache->valid ) || ( 1 == cache->expired ) );

    /*
     * call user code
     */
    return inetNetToMediaTable_container_load( ( Container_Container* )cache->magic );
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free( Cache* cache, void* magic )
{
    Container_Container* container;

    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_cache_free", "called\n" ) );

    if ( ( NULL == cache ) || ( NULL == cache->magic ) ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid cache in inetNetToMediaTable_cache_free\n" );
        return;
    }

    container = ( Container_Container* )cache->magic;

    _container_free( container );
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free( inetNetToMediaTable_rowreq_ctx* rowreq_ctx,
    void* context )
{
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_container_item_free",
        "called\n" ) );

    if ( NULL == rowreq_ctx )
        return;

    inetNetToMediaTable_release_rowreq_ctx( rowreq_ctx );
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free( Container_Container* container )
{
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_container_free",
        "called\n" ) );

    if ( NULL == container ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid container in inetNetToMediaTable_container_free\n" );
        return;
    }

    /*
     * call user code
     */
    inetNetToMediaTable_container_free( container );

    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR( container,
        ( Container_FuncObjFunc* )_container_item_free,
        NULL );
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void _inetNetToMediaTable_container_init( inetNetToMediaTable_interface_ctx*
        if_ctx )
{
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_container_init", "called\n" ) );

    /*
     * cache init
     */
    if_ctx->cache = CacheHandler_create( 30, /* timeout in seconds */
        _cache_load, _cache_free,
        inetNetToMediaTable_oid,
        inetNetToMediaTable_oid_size );

    if ( NULL == if_ctx->cache ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "error creating cache for inetNetToMediaTable\n" );
        return;
    }

    if_ctx->cache->flags = CacheOperation_DONT_INVALIDATE_ON_SET;

    inetNetToMediaTable_container_init( &if_ctx->container, if_ctx->cache );
    if ( NULL == if_ctx->container ) {
        if_ctx->container = Container_find( "inetNetToMediaTable:tableContainer" );
        if ( if_ctx->container )
            if_ctx->container->containerName = strdup( "inetNetToMediaTable" );
    }
    if ( NULL == if_ctx->container ) {
        Logger_log( LOGGER_PRIORITY_ERR, "error creating container in "
                                         "inetNetToMediaTable_container_init\n" );
        return;
    }

    if ( NULL != if_ctx->cache )
        if_ctx->cache->magic = ( void* )if_ctx->container;
} /* _inetNetToMediaTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void _inetNetToMediaTable_container_shutdown( inetNetToMediaTable_interface_ctx*
        if_ctx )
{
    DEBUG_MSGTL( ( "internal:inetNetToMediaTable:_inetNetToMediaTable_container_shutdown", "called\n" ) );

    inetNetToMediaTable_container_shutdown( if_ctx->container );

    _container_free( if_ctx->container );

} /* _inetNetToMediaTable_container_shutdown */

inetNetToMediaTable_rowreq_ctx*
inetNetToMediaTable_row_find_by_mib_index( inetNetToMediaTable_mib_index*
        mib_idx )
{
    inetNetToMediaTable_rowreq_ctx* rowreq_ctx;
    oid oid_tmp[ ASN01_MAX_OID_LEN ];
    Types_Index oid_idx;
    int rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof( oid_tmp ) / sizeof( oid );

    /*
     * convert
     */
    rc = inetNetToMediaTable_index_to_oid( &oid_idx, mib_idx );
    if ( MFD_SUCCESS != rc )
        return NULL;

    rowreq_ctx = ( inetNetToMediaTable_rowreq_ctx* )
        CONTAINER_FIND( inetNetToMediaTable_if_ctx.container, &oid_idx );

    return rowreq_ctx;
}
