/*
 * Note: this file originally auto-generated by mib2c 
 */
#ifndef NSTRANSACTIONTABLE_H
#define NSTRANSACTIONTABLE_H

#include "AgentHandler.h"
#include "TableIterator.h"
/*
 * function declarations 
 */
void            init_nsTransactionTable(void);
void            initialize_table_nsTransactionTable(void);
NodeHandlerFT nsTransactionTable_handler;
FirstDataPointFT nsTransactionTable_get_first_data_point;
NextDataPointFT nsTransactionTable_get_next_data_point;

/*
 * column number definitions for table nsTransactionTable 
 */
#define COLUMN_NSTRANSACTIONID		1
#define COLUMN_NSTRANSACTIONMODE		2
#endif                          /* NSTRANSACTIONTABLE_H */
