/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent. 
 */


#ifndef _MIBGROUP_SNMPNOTIFYFILTERPROFILETABLE_H
#define _MIBGROUP_SNMPNOTIFYFILTERPROFILETABLE_H

#include "Vars.h"
#include "Callback.h"

/*
 * we may use header_complex from the header_complex module 
 */



    /*
     * our storage structure(s) 
     */
     struct snmpNotifyFilterProfileTable_data {

         char           *snmpTargetParamsName;
         size_t          snmpTargetParamsNameLen;
         char           *snmpNotifyFilterProfileName;
         size_t          snmpNotifyFilterProfileNameLen;
         long            snmpNotifyFilterProfileStorType;
         long            snmpNotifyFilterProfileRowStatus;

     };




/*
 * enum definitions from the covered mib sections 
 */








/*
 * function prototypes 
 */


     void            init_snmpNotifyFilterProfileTable(void);
     FindVarMethodFT   var_snmpNotifyFilterProfileTable;
     void            parse_snmpNotifyFilterProfileTable(const char *,
                                                        char *);
     Callback_CallbackFT    store_snmpNotifyFilterProfileTable;

     WriteMethodFT     write_snmpNotifyFilterProfileName;
     WriteMethodFT     write_snmpNotifyFilterProfileStorType;
     WriteMethodFT     write_snmpNotifyFilterProfileRowStatus;

     char           *get_FilterProfileName(const char *paramName,
                                           size_t paramName_len,
                                           size_t * profileName_len);


#endif                          /* _MIBGROUP_SNMPNOTIFYFILTERPROFILETABLE_H */
