#ifndef MODULEINITS_H
#define MODULEINITS_H

/* This file is automatically generated by configure.  Do not modify by hand. */
if ( Vars_shouldInit( "snmpMPDStats_5_5" ) )
    init_snmpMPDStats_5_5();
if ( Vars_shouldInit( "usmStats_5_5" ) )
    init_usmStats_5_5();
if ( Vars_shouldInit( "snmpEngine" ) )
    init_snmpEngine();
if ( Vars_shouldInit( "usmUser" ) )
    init_usmUser();
if ( Vars_shouldInit( "snmp_mib_5_5" ) )
    init_snmp_mib_5_5();
if ( Vars_shouldInit( "system_mib" ) )
    init_system_mib();
if ( Vars_shouldInit( "sysORTable" ) )
    init_sysORTable();
if ( Vars_shouldInit( "vacm_vars" ) )
    init_vacm_vars();
if ( Vars_shouldInit( "setSerialNo" ) )
    init_setSerialNo();
if ( Vars_shouldInit( "at" ) )
    init_at();
if ( Vars_shouldInit( "ip" ) )
    init_ip();
if ( Vars_shouldInit( "tcp" ) )
    init_tcp();
if ( Vars_shouldInit( "icmp" ) )
    init_icmp();
if ( Vars_shouldInit( "udp" ) )
    init_udp();
if ( Vars_shouldInit( "disk_hw" ) )
    init_disk_hw();
if ( Vars_shouldInit( "proc" ) )
    init_proc();
if ( Vars_shouldInit( "versioninfo" ) )
    init_versioninfo();
if ( Vars_shouldInit( "pass" ) )
    init_pass();
if ( Vars_shouldInit( "pass_persist" ) )
    init_pass_persist();
if ( Vars_shouldInit( "loadave" ) )
    init_loadave();
if ( Vars_shouldInit( "extend" ) )
    init_extend();
if ( Vars_shouldInit( "errormib" ) )
    init_errormib();
if ( Vars_shouldInit( "file" ) )
    init_file();
if ( Vars_shouldInit( "dlmod" ) )
    init_dlmod();
if ( Vars_shouldInit( "proxy" ) )
    init_proxy();
if ( Vars_shouldInit( "logmatch" ) )
    init_logmatch();
if ( Vars_shouldInit( "memory" ) )
    init_memory();
if ( Vars_shouldInit( "vmstat" ) )
    init_vmstat();
if ( Vars_shouldInit( "snmpNotifyTable" ) )
    init_snmpNotifyTable();
if ( Vars_shouldInit( "snmpNotifyFilterProfileTable" ) )
    init_snmpNotifyFilterProfileTable();
if ( Vars_shouldInit( "notification_log" ) )
    init_notification_log();
if ( Vars_shouldInit( "target_counters_5_5" ) )
    init_target_counters_5_5();
if ( Vars_shouldInit( "snmpTargetAddrEntry" ) )
    init_snmpTargetAddrEntry();
if ( Vars_shouldInit( "snmpTargetParamsEntry" ) )
    init_snmpTargetParamsEntry();
if ( Vars_shouldInit( "nsTransactionTable" ) )
    init_nsTransactionTable();
if ( Vars_shouldInit( "nsModuleTable" ) )
    init_nsModuleTable();
if ( Vars_shouldInit( "nsDebug" ) )
    init_nsDebug();
if ( Vars_shouldInit( "nsCache" ) )
    init_nsCache();
if ( Vars_shouldInit( "nsLogging" ) )
    init_nsLogging();
if ( Vars_shouldInit( "nsVacmAccessTable" ) )
    init_nsVacmAccessTable();
if ( Vars_shouldInit( "mteScalars" ) )
    init_mteScalars();
if ( Vars_shouldInit( "mteTrigger" ) )
    init_mteTrigger();
if ( Vars_shouldInit( "mteTriggerTable" ) )
    init_mteTriggerTable();
if ( Vars_shouldInit( "mteTriggerDeltaTable" ) )
    init_mteTriggerDeltaTable();
if ( Vars_shouldInit( "mteTriggerExistenceTable" ) )
    init_mteTriggerExistenceTable();
if ( Vars_shouldInit( "mteTriggerBooleanTable" ) )
    init_mteTriggerBooleanTable();
if ( Vars_shouldInit( "mteTriggerThresholdTable" ) )
    init_mteTriggerThresholdTable();
if ( Vars_shouldInit( "mteTriggerConf" ) )
    init_mteTriggerConf();
if ( Vars_shouldInit( "mteEvent" ) )
    init_mteEvent();
if ( Vars_shouldInit( "mteEventTable" ) )
    init_mteEventTable();
if ( Vars_shouldInit( "mteEventSetTable" ) )
    init_mteEventSetTable();
if ( Vars_shouldInit( "mteEventNotificationTable" ) )
    init_mteEventNotificationTable();
if ( Vars_shouldInit( "mteEventConf" ) )
    init_mteEventConf();
if ( Vars_shouldInit( "mteObjects" ) )
    init_mteObjects();
if ( Vars_shouldInit( "mteObjectsTable" ) )
    init_mteObjectsTable();
if ( Vars_shouldInit( "mteObjectsConf" ) )
    init_mteObjectsConf();
if ( Vars_shouldInit( "schedCore" ) )
    init_schedCore();
if ( Vars_shouldInit( "schedConf" ) )
    init_schedConf();
if ( Vars_shouldInit( "schedTable" ) )
    init_schedTable();
if ( Vars_shouldInit( "override" ) )
    init_override();
if ( Vars_shouldInit( "hrh_storage" ) )
    init_hrh_storage();
if ( Vars_shouldInit( "hrh_filesys" ) )
    init_hrh_filesys();
if ( Vars_shouldInit( "hrSWInstalledTable" ) )
    init_hrSWInstalledTable();
if ( Vars_shouldInit( "hrSWRunTable" ) )
    init_hrSWRunTable();
if ( Vars_shouldInit( "hr_system" ) )
    init_hr_system();
if ( Vars_shouldInit( "hr_device" ) )
    init_hr_device();
if ( Vars_shouldInit( "hr_other" ) )
    init_hr_other();
if ( Vars_shouldInit( "hr_proc" ) )
    init_hr_proc();
if ( Vars_shouldInit( "hr_network" ) )
    init_hr_network();
if ( Vars_shouldInit( "hr_print" ) )
    init_hr_print();
if ( Vars_shouldInit( "hr_disk" ) )
    init_hr_disk();
if ( Vars_shouldInit( "hr_partition" ) )
    init_hr_partition();
if ( Vars_shouldInit( "vacm_context" ) )
    init_vacm_context();
if ( Vars_shouldInit( "var_route" ) )
    init_var_route();
if ( Vars_shouldInit( "tcpTable" ) )
    init_tcpTable();
if ( Vars_shouldInit( "udpTable" ) )
    init_udpTable();
if ( Vars_shouldInit( "ip_scalars" ) )
    init_ip_scalars();
if ( Vars_shouldInit( "snmpNotifyFilterTable" ) )
    init_snmpNotifyFilterTable();
if ( Vars_shouldInit( "swinst" ) )
    init_swinst();
if ( Vars_shouldInit( "swrun" ) )
    init_swrun();
if ( Vars_shouldInit( "hrSWRunPerfTable" ) )
    init_hrSWRunPerfTable();
if ( Vars_shouldInit( "ifTable" ) )
    init_ifTable();
if ( Vars_shouldInit( "ifXTable" ) )
    init_ifXTable();
if ( Vars_shouldInit( "ipAddressTable" ) )
    init_ipAddressTable();
if ( Vars_shouldInit( "ipAddressPrefixTable" ) )
    init_ipAddressPrefixTable();
if ( Vars_shouldInit( "ipDefaultRouterTable" ) )
    init_ipDefaultRouterTable();
if ( Vars_shouldInit( "inetNetToMediaTable" ) )
    init_inetNetToMediaTable();
if ( Vars_shouldInit( "ipSystemStatsTable" ) )
    init_ipSystemStatsTable();
if ( Vars_shouldInit( "ipv6ScopeZoneIndexTable" ) )
    init_ipv6ScopeZoneIndexTable();
if ( Vars_shouldInit( "ipIfStatsTable" ) )
    init_ipIfStatsTable();
if ( Vars_shouldInit( "ipCidrRouteTable" ) )
    init_ipCidrRouteTable();
if ( Vars_shouldInit( "inetCidrRouteTable" ) )
    init_inetCidrRouteTable();
if ( Vars_shouldInit( "tcpConnectionTable" ) )
    init_tcpConnectionTable();
if ( Vars_shouldInit( "tcpListenerTable" ) )
    init_tcpListenerTable();
if ( Vars_shouldInit( "udpEndpointTable" ) )
    init_udpEndpointTable();
if ( Vars_shouldInit( "hw_fsys" ) )
    init_hw_fsys();
if ( Vars_shouldInit( "hw_mem" ) )
    init_hw_mem();
if ( Vars_shouldInit( "cpu" ) )
    init_cpu();
if ( Vars_shouldInit( "cpu_linux" ) )
    init_cpu_linux();
if ( Vars_shouldInit( "interface" ) )
    init_interface();

#endif // MODULEINITS_H
