/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id$
 */
#ifndef TCPCONNECTIONTABLE_DATA_ACCESS_H
#define TCPCONNECTIONTABLE_DATA_ACCESS_H

#include "CacheHandler.h"
#include "RowMerge.h"
#include "System/Containers/Container.h"
#include "System/Util/VariableList.h"
#include "TableContainer.h"

/*
     *********************************************************************
     * function declarations
     */

/*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table tcpConnectionTable
 ***
 **********************************************************************
 **********************************************************************/
/*
     * TCP-MIB::tcpConnectionTable is subid 19 of tcp.
     * Its status is Current.
     * OID: .1.3.6.1.2.1.6.19, length: 8
     */

int tcpConnectionTable_init_data( tcpConnectionTable_registration*
        tcpConnectionTable_reg );

/*
     * TODO:180:o: Review tcpConnectionTable cache timeout.
     * The number of seconds before the cache times out
     */
#define TCPCONNECTIONTABLE_CACHE_TIMEOUT 60

void tcpConnectionTable_container_init( Container_Container** container_ptr_ptr,
    Cache* cache );
void tcpConnectionTable_container_shutdown( Container_Container* container_ptr );

int tcpConnectionTable_container_load( Container_Container* container );
void tcpConnectionTable_container_free( Container_Container* container );

int tcpConnectionTable_cache_load( Container_Container* container );
void tcpConnectionTable_cache_free( Container_Container* container );

int tcpConnectionTable_row_prep( tcpConnectionTable_rowreq_ctx*
        rowreq_ctx );

#endif /* TCPCONNECTIONTABLE_DATA_ACCESS_H */
