/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.17 $ of : mfd-data-access.m2c,v $
 *
 * $Id$
 */
#ifndef IPCIDRROUTETABLE_DATA_ACCESS_H
#define IPCIDRROUTETABLE_DATA_ACCESS_H

#include "Container.h"
#include "ipCidrRouteTable.h"
#include "CacheHandler.h"

    /*
     *********************************************************************
     * function declarations
     */

    /*
     *********************************************************************
     * Table declarations
     */
/**********************************************************************
 **********************************************************************
 ***
 *** Table ipCidrRouteTable
 ***
 **********************************************************************
 **********************************************************************/
    /*
     * IP-FORWARD-MIB::ipCidrRouteTable is subid 4 of ipForward.
     * Its status is Deprecated.
     * OID: .1.3.6.1.2.1.4.24.4, length: 9
     */


    int
        ipCidrRouteTable_init_data(ipCidrRouteTable_registration *
                                   ipCidrRouteTable_reg);


    /*
     * TODO:180:o: Review ipCidrRouteTable cache timeout.
     * The number of seconds before the cache times out
     */
#define IPCIDRROUTETABLE_CACHE_TIMEOUT   60

    void            ipCidrRouteTable_container_init(Container_Container
                                                    **container_ptr_ptr,
                                                    Cache * cache);
    void            ipCidrRouteTable_container_shutdown(Container_Container
                                                        *container_ptr);

    int             ipCidrRouteTable_container_load(Container_Container
                                                    *container);
    void            ipCidrRouteTable_container_free(Container_Container
                                                    *container);

    int             ipCidrRouteTable_cache_load(Container_Container
                                                *container);
    void            ipCidrRouteTable_cache_free(Container_Container
                                                *container);

    int             ipCidrRouteTable_row_prep(ipCidrRouteTable_rowreq_ctx *
                                              rowreq_ctx);

    int
        ipCidrRouteTable_validate_index(ipCidrRouteTable_registration *
                                        ipCidrRouteTable_reg,
                                        ipCidrRouteTable_rowreq_ctx *
                                        rowreq_ctx);
    int             ipCidrRouteDest_check_index(ipCidrRouteTable_rowreq_ctx * rowreq_ctx);      /* internal */
    int             ipCidrRouteMask_check_index(ipCidrRouteTable_rowreq_ctx * rowreq_ctx);      /* internal */
    int             ipCidrRouteTos_check_index(ipCidrRouteTable_rowreq_ctx * rowreq_ctx);       /* internal */
    int             ipCidrRouteNextHop_check_index(ipCidrRouteTable_rowreq_ctx * rowreq_ctx);   /* internal */


#endif                          /* IPCIDRROUTETABLE_DATA_ACCESS_H */
