/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.67 $ of : mfd-interface.m2c,v $ 
 *
 * $Id$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

#include "inetCidrRouteTable_interface.h"
#include "BabySteps.h"
#include "Client.h"
#include "Mib.h"
#include "RowMerge.h"
#include "System/Containers/ContainerBinaryArray.h"
#include "System/Util/Assert.h"
#include "System/Util/Trace.h"
#include "System/Util/Logger.h"
#include "TableContainer.h"
#include "System/Util/VariableList.h"
#include "inetCidrRouteTable_constants.h"
#include "inetCidrRouteTable_data_access.h"
#include "siglog/agent/mfd.h"

/**********************************************************************
 **********************************************************************
 ***
 *** Table inetCidrRouteTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * IP-FORWARD-MIB::inetCidrRouteTable is subid 7 of ipForward.
 * Its status is Current.
 * OID: .1.3.6.1.2.1.4.24.7, length: 9
 */
typedef struct inetCidrRouteTable_interface_ctx_s {

    Container_Container* container;
    Cache* cache;

    inetCidrRouteTable_registration* user_ctx;

    TableRegistrationInfo tbl_info;

    BabyStepsAccessMethods access_multiplexer;

    u_int table_dirty;

} inetCidrRouteTable_interface_ctx;

static inetCidrRouteTable_interface_ctx inetCidrRouteTable_if_ctx;

static void
_inetCidrRouteTable_container_init( inetCidrRouteTable_interface_ctx*
        if_ctx );
static void
_inetCidrRouteTable_container_shutdown( inetCidrRouteTable_interface_ctx*
        if_ctx );

Container_Container*
inetCidrRouteTable_container_get( void )
{
    return inetCidrRouteTable_if_ctx.container;
}

inetCidrRouteTable_registration*
inetCidrRouteTable_registration_get( void )
{
    return inetCidrRouteTable_if_ctx.user_ctx;
}

inetCidrRouteTable_registration*
inetCidrRouteTable_registration_set( inetCidrRouteTable_registration*
        newreg )
{
    inetCidrRouteTable_registration* old = inetCidrRouteTable_if_ctx.user_ctx;
    inetCidrRouteTable_if_ctx.user_ctx = newreg;
    return old;
}

int inetCidrRouteTable_container_size( void )
{
    return CONTAINER_SIZE( inetCidrRouteTable_if_ctx.container );
}

u_int inetCidrRouteTable_dirty_get( void )
{
    return inetCidrRouteTable_if_ctx.table_dirty;
}

void inetCidrRouteTable_dirty_set( u_int status )
{
    DEBUG_MSGTL( ( "inetCidrRouteTable:inetCidrRouteTable_dirty_set",
        "called. was %d, now %d\n",
        inetCidrRouteTable_if_ctx.table_dirty, status ) );
    inetCidrRouteTable_if_ctx.table_dirty = status;
}

Cache*
inetCidrRouteTable_get_cache( void )
{
    return inetCidrRouteTable_if_ctx.cache;
}

/*
 * mfd multiplexer modes
 */
static NodeHandlerFT _mfd_inetCidrRouteTable_pre_request;
static NodeHandlerFT _mfd_inetCidrRouteTable_post_request;
static NodeHandlerFT _mfd_inetCidrRouteTable_object_lookup;
static NodeHandlerFT _mfd_inetCidrRouteTable_get_values;
static NodeHandlerFT _mfd_inetCidrRouteTable_check_objects;
static NodeHandlerFT _mfd_inetCidrRouteTable_undo_setup;
static NodeHandlerFT _mfd_inetCidrRouteTable_set_values;
static NodeHandlerFT _mfd_inetCidrRouteTable_undo_cleanup;
static NodeHandlerFT _mfd_inetCidrRouteTable_undo_values;
static NodeHandlerFT _mfd_inetCidrRouteTable_commit;
static NodeHandlerFT _mfd_inetCidrRouteTable_undo_commit;
static NodeHandlerFT _mfd_inetCidrRouteTable_irreversible_commit;
static NodeHandlerFT _mfd_inetCidrRouteTable_check_dependencies;

static inline int
_inetCidrRouteTable_check_indexes( inetCidrRouteTable_rowreq_ctx* rowreq_ctx );
/**
 * @internal
 * Initialize the table inetCidrRouteTable 
 *    (Define its contents and how it's structured)
 */
void _inetCidrRouteTable_initialize_interface( inetCidrRouteTable_registration*
                                                   reg_ptr,
    u_long flags )
{
    BabyStepsAccessMethods* access_multiplexer = &inetCidrRouteTable_if_ctx.access_multiplexer;
    TableRegistrationInfo* tbl_info = &inetCidrRouteTable_if_ctx.tbl_info;
    HandlerRegistration* reginfo;
    MibHandler* handler;
    int mfd_modes = 0;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_initialize_interface", "called\n" ) );

    /*************************************************
     *
     * save interface context for inetCidrRouteTable
     */
    /*
     * Setting up the table's definition
     */
    Table_helperAddIndexes( tbl_info, asnINTEGER,
        /** index: inetCidrRouteDestType */
        asnOCTET_STR,
        /** index: inetCidrRouteDest */
        asnUNSIGNED,
        /** index: inetCidrRoutePfxLen */
        asnOBJECT_ID,
        /** index: inetCidrRoutePolicy */
        asnINTEGER,
        /** index: inetCidrRouteNextHopType */
        asnOCTET_STR,
        /** index: inetCidrRouteNextHop */
        0 );

    /*
     * Define the minimum and maximum accessible columns.  This
     * optimizes retrieval. 
     */
    tbl_info->min_column = INETCIDRROUTETABLE_MIN_COL;
    tbl_info->max_column = INETCIDRROUTETABLE_MAX_COL;

    /*
     * save users context
     */
    inetCidrRouteTable_if_ctx.user_ctx = reg_ptr;

    /*
     * call data access initialization code
     */
    inetCidrRouteTable_init_data( reg_ptr );

    /*
     * set up the container
     */
    _inetCidrRouteTable_container_init( &inetCidrRouteTable_if_ctx );
    if ( NULL == inetCidrRouteTable_if_ctx.container ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "could not initialize container for inetCidrRouteTable\n" );
        return;
    }

    /*
     * access_multiplexer: REQUIRED wrapper for get request handling
     */
    access_multiplexer->object_lookup = _mfd_inetCidrRouteTable_object_lookup;
    access_multiplexer->get_values = _mfd_inetCidrRouteTable_get_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->pre_request = _mfd_inetCidrRouteTable_pre_request;
    access_multiplexer->post_request = _mfd_inetCidrRouteTable_post_request;

    /*
     * REQUIRED wrappers for set request handling
     */
    access_multiplexer->object_syntax_checks = _mfd_inetCidrRouteTable_check_objects;
    access_multiplexer->undo_setup = _mfd_inetCidrRouteTable_undo_setup;
    access_multiplexer->undo_cleanup = _mfd_inetCidrRouteTable_undo_cleanup;
    access_multiplexer->set_values = _mfd_inetCidrRouteTable_set_values;
    access_multiplexer->undo_sets = _mfd_inetCidrRouteTable_undo_values;

    /*
     * no wrappers yet
     */
    access_multiplexer->commit = _mfd_inetCidrRouteTable_commit;
    access_multiplexer->undo_commit = _mfd_inetCidrRouteTable_undo_commit;
    access_multiplexer->irreversible_commit = _mfd_inetCidrRouteTable_irreversible_commit;

    /*
     * REQUIRED for tables with dependencies
     */
    access_multiplexer->consistency_checks = _mfd_inetCidrRouteTable_check_dependencies;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
    DEBUG_MSGTL( ( "inetCidrRouteTable:init_inetCidrRouteTable",
        "Registering inetCidrRouteTable as a mibs-for-dummies table.\n" ) );
    handler = BabySteps_accessMultiplexerGet( access_multiplexer );
    reginfo = AgentHandler_registrationCreate( "inetCidrRouteTable", handler,
        inetCidrRouteTable_oid,
        inetCidrRouteTable_oid_size,
        HANDLER_CAN_BABY_STEP
            | HANDLER_CAN_RWRITE );
    if ( NULL == reginfo ) {
        Logger_log( LOGGER_PRIORITY_ERR, "error registering table inetCidrRouteTable\n" );
        return;
    }
    reginfo->my_reg_void = &inetCidrRouteTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
    if ( access_multiplexer->object_lookup )
        mfd_modes |= BabyStepsMode_OBJECT_LOOKUP;
    if ( access_multiplexer->pre_request )
        mfd_modes |= BabyStepsMode_PRE_REQUEST;
    if ( access_multiplexer->post_request )
        mfd_modes |= BabyStepsMode_POST_REQUEST;

    if ( access_multiplexer->set_values )
        mfd_modes |= BabyStepsMode_SET_VALUES;
    if ( access_multiplexer->irreversible_commit )
        mfd_modes |= BabyStepsMode_IRREVERSIBLE_COMMIT;
    if ( access_multiplexer->object_syntax_checks )
        mfd_modes |= BabyStepsMode_CHECK_OBJECT;

    if ( access_multiplexer->undo_setup )
        mfd_modes |= BabyStepsMode_UNDO_SETUP;
    if ( access_multiplexer->undo_cleanup )
        mfd_modes |= BabyStepsMode_UNDO_CLEANUP;
    if ( access_multiplexer->undo_sets )
        mfd_modes |= BabyStepsMode_UNDO_SETS;

    if ( access_multiplexer->row_creation )
        mfd_modes |= BabyStepsMode_ROW_CREATE;
    if ( access_multiplexer->consistency_checks )
        mfd_modes |= BabyStepsMode_CHECK_CONSISTENCY;
    if ( access_multiplexer->commit )
        mfd_modes |= BabyStepsMode_COMMIT;
    if ( access_multiplexer->undo_commit )
        mfd_modes |= BabyStepsMode_UNDO_COMMIT;

    handler = BabySteps_handlerGet( mfd_modes );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
    handler = RowMerge_getRowMergeHandler( reginfo->rootoid_len + 2 );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject container_table helper
     */
    handler = TableContainer_handlerGet( tbl_info,
        inetCidrRouteTable_if_ctx.container,
        TABLE_CONTAINER_KEY_NETSNMP_INDEX );
    AgentHandler_injectHandler( reginfo, handler );

    /*************************************************
     *
     * inject cache helper
     */
    if ( NULL != inetCidrRouteTable_if_ctx.cache ) {
        handler = CacheHandler_handlerGet( inetCidrRouteTable_if_ctx.cache );
        AgentHandler_injectHandler( reginfo, handler );
    }

    /*
     * register table
     */
    Table_registerTable( reginfo, tbl_info );

} /* _inetCidrRouteTable_initialize_interface */

/**
 * @internal
 * Shutdown the table inetCidrRouteTable
 */
void _inetCidrRouteTable_shutdown_interface( inetCidrRouteTable_registration*
        reg_ptr )
{
    /*
     * shutdown the container
     */
    _inetCidrRouteTable_container_shutdown( &inetCidrRouteTable_if_ctx );
}

void inetCidrRouteTable_valid_columns_set( ColumnInfo* vc )
{
    inetCidrRouteTable_if_ctx.tbl_info.valid_columns = vc;
} /* inetCidrRouteTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int inetCidrRouteTable_index_to_oid( Types_Index* oid_idx,
    inetCidrRouteTable_mib_index* mib_idx )
{
    int err = PRIOT_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * inetCidrRouteDestType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    VariableList var_inetCidrRouteDestType;
    /*
     * inetCidrRouteDest(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    VariableList var_inetCidrRouteDest;
    /*
     * inetCidrRoutePfxLen(3)/InetAddressPrefixLength/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H
     */
    VariableList var_inetCidrRoutePfxLen;
    /*
     * inetCidrRoutePolicy(4)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/a/w/e/r/d/h
     */
    VariableList var_inetCidrRoutePolicy;
    /*
     * inetCidrRouteNextHopType(5)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    VariableList var_inetCidrRouteNextHopType;
    /*
     * inetCidrRouteNextHop(6)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    VariableList var_inetCidrRouteNextHop;

    /*
     * set up varbinds
     */
    memset( &var_inetCidrRouteDestType, 0x00,
        sizeof( var_inetCidrRouteDestType ) );
    var_inetCidrRouteDestType.type = asnINTEGER;
    memset( &var_inetCidrRouteDest, 0x00, sizeof( var_inetCidrRouteDest ) );
    var_inetCidrRouteDest.type = asnOCTET_STR;
    memset( &var_inetCidrRoutePfxLen, 0x00,
        sizeof( var_inetCidrRoutePfxLen ) );
    var_inetCidrRoutePfxLen.type = asnUNSIGNED;
    memset( &var_inetCidrRoutePolicy, 0x00,
        sizeof( var_inetCidrRoutePolicy ) );
    var_inetCidrRoutePolicy.type = asnOBJECT_ID;
    memset( &var_inetCidrRouteNextHopType, 0x00,
        sizeof( var_inetCidrRouteNextHopType ) );
    var_inetCidrRouteNextHopType.type = asnINTEGER;
    memset( &var_inetCidrRouteNextHop, 0x00,
        sizeof( var_inetCidrRouteNextHop ) );
    var_inetCidrRouteNextHop.type = asnOCTET_STR;

    /*
     * chain temp index varbinds together
     */
    var_inetCidrRouteDestType.next = &var_inetCidrRouteDest;
    var_inetCidrRouteDest.next = &var_inetCidrRoutePfxLen;
    var_inetCidrRoutePfxLen.next = &var_inetCidrRoutePolicy;
    var_inetCidrRoutePolicy.next = &var_inetCidrRouteNextHopType;
    var_inetCidrRouteNextHopType.next = &var_inetCidrRouteNextHop;
    var_inetCidrRouteNextHop.next = NULL;

    DEBUG_MSGTL( ( "verbose:inetCidrRouteTable:inetCidrRouteTable_index_to_oid", "called\n" ) );

    /*
     * inetCidrRouteDestType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    Client_setVarValue( &var_inetCidrRouteDestType,
        ( u_char* )&mib_idx->inetCidrRouteDestType,
        sizeof( mib_idx->inetCidrRouteDestType ) );

    /*
     * inetCidrRouteDest(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    Client_setVarValue( &var_inetCidrRouteDest,
        ( u_char* )&mib_idx->inetCidrRouteDest,
        mib_idx->inetCidrRouteDest_len * sizeof( mib_idx->inetCidrRouteDest[ 0 ] ) );

    /*
     * inetCidrRoutePfxLen(3)/InetAddressPrefixLength/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H 
     */
    Client_setVarValue( &var_inetCidrRoutePfxLen,
        ( u_char* )&mib_idx->inetCidrRoutePfxLen,
        sizeof( mib_idx->inetCidrRoutePfxLen ) );

    /*
     * inetCidrRoutePolicy(4)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/a/w/e/r/d/h 
     */
    Client_setVarValue( &var_inetCidrRoutePolicy,
        ( u_char* )&mib_idx->inetCidrRoutePolicy,
        mib_idx->inetCidrRoutePolicy_len * sizeof( mib_idx->inetCidrRoutePolicy[ 0 ] ) );

    /*
     * inetCidrRouteNextHopType(5)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    Client_setVarValue( &var_inetCidrRouteNextHopType,
        ( u_char* )&mib_idx->inetCidrRouteNextHopType,
        sizeof( mib_idx->inetCidrRouteNextHopType ) );

    /*
     * inetCidrRouteNextHop(6)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    Client_setVarValue( &var_inetCidrRouteNextHop,
        ( u_char* )&mib_idx->inetCidrRouteNextHop,
        mib_idx->inetCidrRouteNextHop_len * sizeof( mib_idx->inetCidrRouteNextHop[ 0 ] ) );

    err = Mib_buildOidNoalloc( oid_idx->oids, oid_idx->len, &oid_idx->len,
        NULL, 0, &var_inetCidrRouteDestType );
    if ( err )
        Logger_log( LOGGER_PRIORITY_ERR, "error %d converting index to oid\n", err );

    /*
     * parsing may have allocated memory. free it.
     */
    Client_resetVarBuffers( &var_inetCidrRouteDestType );

    return err;
} /* inetCidrRouteTable_index_to_oid */

/**
 * extract inetCidrRouteTable indexes from a Types_Index
 *
 * @retval PRIOT_ERR_NOERROR  : no error
 * @retval ErrorCode_GENERR   : error
 */
int inetCidrRouteTable_index_from_oid( Types_Index* oid_idx,
    inetCidrRouteTable_mib_index* mib_idx )
{
    int err = PRIOT_ERR_NOERROR;

    /*
     * temp storage for parsing indexes
     */
    /*
     * inetCidrRouteDestType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    VariableList var_inetCidrRouteDestType;
    /*
     * inetCidrRouteDest(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    VariableList var_inetCidrRouteDest;
    /*
     * inetCidrRoutePfxLen(3)/InetAddressPrefixLength/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H
     */
    VariableList var_inetCidrRoutePfxLen;
    /*
     * inetCidrRoutePolicy(4)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/a/w/e/r/d/h
     */
    VariableList var_inetCidrRoutePolicy;
    /*
     * inetCidrRouteNextHopType(5)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h
     */
    VariableList var_inetCidrRouteNextHopType;
    /*
     * inetCidrRouteNextHop(6)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h
     */
    VariableList var_inetCidrRouteNextHop;

    /*
     * set up varbinds
     */
    memset( &var_inetCidrRouteDestType, 0x00,
        sizeof( var_inetCidrRouteDestType ) );
    var_inetCidrRouteDestType.type = asnINTEGER;
    memset( &var_inetCidrRouteDest, 0x00, sizeof( var_inetCidrRouteDest ) );
    var_inetCidrRouteDest.type = asnOCTET_STR;
    memset( &var_inetCidrRoutePfxLen, 0x00,
        sizeof( var_inetCidrRoutePfxLen ) );
    var_inetCidrRoutePfxLen.type = asnUNSIGNED;
    memset( &var_inetCidrRoutePolicy, 0x00,
        sizeof( var_inetCidrRoutePolicy ) );
    var_inetCidrRoutePolicy.type = asnOBJECT_ID;
    memset( &var_inetCidrRouteNextHopType, 0x00,
        sizeof( var_inetCidrRouteNextHopType ) );
    var_inetCidrRouteNextHopType.type = asnINTEGER;
    memset( &var_inetCidrRouteNextHop, 0x00,
        sizeof( var_inetCidrRouteNextHop ) );
    var_inetCidrRouteNextHop.type = asnOCTET_STR;

    /*
     * chain temp index varbinds together
     */
    var_inetCidrRouteDestType.next = &var_inetCidrRouteDest;
    var_inetCidrRouteDest.next = &var_inetCidrRoutePfxLen;
    var_inetCidrRoutePfxLen.next = &var_inetCidrRoutePolicy;
    var_inetCidrRoutePolicy.next = &var_inetCidrRouteNextHopType;
    var_inetCidrRouteNextHopType.next = &var_inetCidrRouteNextHop;
    var_inetCidrRouteNextHop.next = NULL;

    DEBUG_MSGTL( ( "verbose:inetCidrRouteTable:inetCidrRouteTable_index_from_oid", "called\n" ) );

    /*
     * parse the oid into the individual index components
     */
    err = Mib_parseOidIndexes( oid_idx->oids, oid_idx->len,
        &var_inetCidrRouteDestType );
    if ( err == PRIOT_ERR_NOERROR ) {
        /*
         * copy out values
         */
        mib_idx->inetCidrRouteDestType = *( ( u_long* )var_inetCidrRouteDestType.value.string );
        /*
         * NOTE: val_len is in bytes, inetCidrRouteDest_len might not be
         */
        if ( var_inetCidrRouteDest.valueLength > sizeof( mib_idx->inetCidrRouteDest ) )
            err = ErrorCode_GENERR;
        else {
            memcpy( mib_idx->inetCidrRouteDest,
                var_inetCidrRouteDest.value.string,
                var_inetCidrRouteDest.valueLength );
            mib_idx->inetCidrRouteDest_len = var_inetCidrRouteDest.valueLength / sizeof( mib_idx->inetCidrRouteDest[ 0 ] );
        }
        mib_idx->inetCidrRoutePfxLen = *( ( u_long* )var_inetCidrRoutePfxLen.value.string );
        /*
         * NOTE: val_len is in bytes, inetCidrRoutePolicy_len might not be
         */
        if ( var_inetCidrRoutePolicy.valueLength > sizeof( mib_idx->inetCidrRoutePolicy ) )
            err = ErrorCode_GENERR;
        else {
            memcpy( mib_idx->inetCidrRoutePolicy,
                var_inetCidrRoutePolicy.value.string,
                var_inetCidrRoutePolicy.valueLength );
            mib_idx->inetCidrRoutePolicy_len = var_inetCidrRoutePolicy.valueLength / sizeof( mib_idx->inetCidrRoutePolicy[ 0 ] );
        }
        mib_idx->inetCidrRouteNextHopType = *( ( u_long* )var_inetCidrRouteNextHopType.value.string );
        /*
         * NOTE: val_len is in bytes, inetCidrRouteNextHop_len might not be
         */
        if ( var_inetCidrRouteNextHop.valueLength > sizeof( mib_idx->inetCidrRouteNextHop ) )
            err = ErrorCode_GENERR;
        else {
            memcpy( mib_idx->inetCidrRouteNextHop,
                var_inetCidrRouteNextHop.value.string,
                var_inetCidrRouteNextHop.valueLength );
            mib_idx->inetCidrRouteNextHop_len = var_inetCidrRouteNextHop.valueLength / sizeof( mib_idx->inetCidrRouteNextHop[ 0 ] );
        }
    }

    /*
     * parsing may have allocated memory. free it.
     */
    Client_resetVarBuffers( &var_inetCidrRouteDestType );

    return err;
} /* inetCidrRouteTable_index_from_oid */

/*
 *********************************************************************
 * @internal
 * allocate resources for a inetCidrRouteTable_rowreq_ctx
 */
inetCidrRouteTable_rowreq_ctx*
inetCidrRouteTable_allocate_rowreq_ctx( inetCidrRouteTable_data* data,
    void* user_init_ctx )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = MEMORY_MALLOC_TYPEDEF( inetCidrRouteTable_rowreq_ctx );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:inetCidrRouteTable_allocate_rowreq_ctx", "called\n" ) );

    if ( NULL == rowreq_ctx ) {
        Logger_log( LOGGER_PRIORITY_ERR, "Couldn't allocate memory for a "
                                         "inetCidrRouteTable_rowreq_ctx.\n" );
        return NULL;
    } else {
        if ( NULL != data ) {
            /*
             * track if we got data from user
             */
            rowreq_ctx->rowreq_flags |= MFD_ROW_DATA_FROM_USER;
            rowreq_ctx->data = data;
        } else if ( NULL == ( rowreq_ctx->data = inetCidrRouteTable_allocate_data() ) ) {
            MEMORY_FREE( rowreq_ctx );
            return NULL;
        }
    }

    /*
     * undo context will be allocated when needed (in *_undo_setup)
     */

    rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

    rowreq_ctx->inetCidrRouteTable_data_list = NULL;

    /*
     * if we allocated data, call init routine
     */
    if ( !( rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER ) ) {
        if ( ErrorCode_SUCCESS != inetCidrRouteTable_rowreq_ctx_init( rowreq_ctx,
                                      user_init_ctx ) ) {
            inetCidrRouteTable_release_rowreq_ctx( rowreq_ctx );
            rowreq_ctx = NULL;
        }
    }

    return rowreq_ctx;
} /* inetCidrRouteTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a inetCidrRouteTable_rowreq_ctx
 */
void inetCidrRouteTable_release_rowreq_ctx( inetCidrRouteTable_rowreq_ctx*
        rowreq_ctx )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:inetCidrRouteTable_release_rowreq_ctx", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    inetCidrRouteTable_rowreq_ctx_cleanup( rowreq_ctx );

    /*
     * for non-transient data, don't free data we got from the user
     */
    if ( ( rowreq_ctx->data ) && !( rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER ) )
        inetCidrRouteTable_release_data( rowreq_ctx->data );

    if ( rowreq_ctx->undo )
        inetCidrRouteTable_release_data( rowreq_ctx->undo );

    /*
     * free index oid pointer
     */
    if ( rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp )
        free( rowreq_ctx->oid_idx.oids );

    MEMORY_FREE( rowreq_ctx );
} /* inetCidrRouteTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetCidrRouteTable_pre_request( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_pre_request", "called\n" ) );

    if ( 1 != RowMerge_statusFirst( reginfo, agtreq_info ) ) {
        DEBUG_MSGTL( ( "internal:inetCidrRouteTable",
            "skipping additional pre_request\n" ) );
        return PRIOT_ERR_NOERROR;
    }

    rc = inetCidrRouteTable_pre_request( inetCidrRouteTable_if_ctx.user_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetCidrRouteTable", "error %d from "
                                             "inetCidrRouteTable_pre_request\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetCidrRouteTable_post_request( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    int rc, packet_rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_post_request", "called\n" ) );

    /*
     * release row context, if deleted
     */
    if ( rowreq_ctx && ( rowreq_ctx->rowreq_flags & MFD_ROW_DELETED ) )
        inetCidrRouteTable_release_rowreq_ctx( rowreq_ctx );

    /*
     * wait for last call before calling user
     */
    if ( 1 != RowMerge_statusLast( reginfo, agtreq_info ) ) {
        DEBUG_MSGTL( ( "internal:inetCidrRouteTable",
            "waiting for last post_request\n" ) );
        return PRIOT_ERR_NOERROR;
    }

    packet_rc = Agent_checkAllRequestsError( agtreq_info->asp, 0 );
    if ( ( MFD_SUCCESS != packet_rc ) && inetCidrRouteTable_dirty_get() ) {
        /*
         * we shouldn't get here. the undo steps should also clear
         * the dirty flags.
         */
        Logger_log( LOGGER_PRIORITY_WARNING,
            "inetCidrRouteTable dirty flag set in post_request "
            "but status != SUCCESS.\n" );
    }

    rc = inetCidrRouteTable_post_request( inetCidrRouteTable_if_ctx.user_ctx, packet_rc );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetCidrRouteTable", "error %d from "
                                             "inetCidrRouteTable_post_request\n",
            rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_post_request */

/**
 * @internal
 * wrapper
 */
static inetCidrRouteTable_rowreq_ctx*
_mfd_inetCidrRouteTable_rowreq_from_index( Types_Index* oid_idx,
    int* rc_ptr )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx;
    inetCidrRouteTable_mib_index mib_idx;
    int rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_rowreq_from_index", "called\n" ) );

    if ( NULL == rc_ptr )
        rc_ptr = &rc;
    *rc_ptr = MFD_SUCCESS;

    memset( &mib_idx, 0x0, sizeof( mib_idx ) );

    /*
     * try to parse oid
     */
    *rc_ptr = inetCidrRouteTable_index_from_oid( oid_idx, &mib_idx );
    if ( MFD_SUCCESS != *rc_ptr ) {
        DEBUG_MSGT( ( "inetCidrRouteTable", "error parsing index\n" ) );
        return NULL;
    }

    /*
     * allocate new context
     */
    rowreq_ctx = inetCidrRouteTable_allocate_rowreq_ctx( NULL, NULL );
    if ( NULL == rowreq_ctx ) {
        *rc_ptr = MFD_ERROR;
        return NULL; /* msg already logged */
    }

    memcpy( &rowreq_ctx->tbl_idx, &mib_idx, sizeof( mib_idx ) );

    /*
     * check indexes
     */
    *rc_ptr = _inetCidrRouteTable_check_indexes( rowreq_ctx );
    if ( MFD_SUCCESS != *rc_ptr ) {
        Assert_assert( ( *rc_ptr == PRIOT_ERR_NOCREATION ) || ( *rc_ptr == PRIOT_ERR_INCONSISTENTNAME ) );
        inetCidrRouteTable_release_rowreq_ctx( rowreq_ctx );
        return NULL;
    }

    /*
     * copy indexes
     */
    rowreq_ctx->oid_idx.len = oid_idx->len;
    memcpy( rowreq_ctx->oid_idx.oids, oid_idx->oids,
        oid_idx->len * sizeof( oid ) );

    return rowreq_ctx;
} /* _mfd_inetCidrRouteTable_rowreq_from_index */

/**
 * @internal
 * wrapper
 */
static int
_mfd_inetCidrRouteTable_object_lookup( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc = PRIOT_ERR_NOERROR;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_object_lookup", "called\n" ) );

    /*
     * get our context from mfd
     * inetCidrRouteTable_interface_ctx *if_ctx =
     *             (inetCidrRouteTable_interface_ctx *)reginfo->my_reg_void;
     */

    if ( NULL == rowreq_ctx ) {
        TableRequestInfo* tblreq_info;
        Types_Index oid_idx;

        tblreq_info = Table_extractTableInfo( requests );
        if ( NULL == tblreq_info ) {
            Logger_log( LOGGER_PRIORITY_ERR, "request had no table info\n" );
            return MFD_ERROR;
        }

        /*
         * try create rowreq
         */
        oid_idx.oids = tblreq_info->index_oid;
        oid_idx.len = tblreq_info->index_oid_len;

        rowreq_ctx = _mfd_inetCidrRouteTable_rowreq_from_index( &oid_idx, &rc );
        if ( MFD_SUCCESS == rc ) {
            Assert_assert( NULL != rowreq_ctx );
            rowreq_ctx->rowreq_flags |= MFD_ROW_CREATED;
            /*
             * add rowreq_ctx to request data lists
             */
            TableContainer_rowInsert( requests, ( Types_Index* )
                                                    rowreq_ctx );
        }
    }

    if ( MFD_SUCCESS != rc )
        Agent_requestSetErrorAll( requests, rc );
    else
        inetCidrRouteTable_row_prep( rowreq_ctx );

    return PRIOT_VALIDATE_ERR( rc );
} /* _mfd_inetCidrRouteTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
static inline int
_inetCidrRouteTable_get_column( inetCidrRouteTable_rowreq_ctx* rowreq_ctx,
    VariableList* var, int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_get_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetCidrRouteIfIndex(7)/InterfaceIndexOrZero/ASN_INTEGER/long(long)//l/A/W/e/R/d/H 
         */
    case COLUMN_INETCIDRROUTEIFINDEX:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteIfIndex_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTETYPE:
        var->valueLength = sizeof( u_long );
        var->type = asnINTEGER;
        rc = inetCidrRouteType_get( rowreq_ctx, ( u_long* )var->value.string );
        break;

    /*
         * inetCidrRouteProto(9)/IANAipRouteProtocol/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTEPROTO:
        var->valueLength = sizeof( u_long );
        var->type = asnINTEGER;
        rc = inetCidrRouteProto_get( rowreq_ctx,
            ( u_long* )var->value.string );
        break;

    /*
         * inetCidrRouteAge(10)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_INETCIDRROUTEAGE:
        var->valueLength = sizeof( u_long );
        var->type = asnGAUGE;
        rc = inetCidrRouteAge_get( rowreq_ctx, ( u_long* )var->value.string );
        break;

    /*
         * inetCidrRouteNextHopAS(11)/InetAutonomousSystemNumber/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/H 
         */
    case COLUMN_INETCIDRROUTENEXTHOPAS:
        var->valueLength = sizeof( u_long );
        var->type = asnUNSIGNED;
        rc = inetCidrRouteNextHopAS_get( rowreq_ctx,
            ( u_long* )var->value.string );
        break;

    /*
         * inetCidrRouteMetric1(12)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC1:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteMetric1_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteMetric2(13)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC2:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteMetric2_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteMetric3(14)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC3:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteMetric3_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteMetric4(15)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC4:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteMetric4_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteMetric5(16)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC5:
        var->valueLength = sizeof( long );
        var->type = asnINTEGER;
        rc = inetCidrRouteMetric5_get( rowreq_ctx,
            ( long* )var->value.string );
        break;

    /*
         * inetCidrRouteStatus(17)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTESTATUS:
        var->valueLength = sizeof( u_long );
        var->type = asnINTEGER;
        rc = inetCidrRouteStatus_get( rowreq_ctx,
            ( u_long* )var->value.string );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetCidrRouteTable_get_column\n",
            column );
        break;
    }

    return rc;
} /* _inetCidrRouteTable_get_column */

int _mfd_inetCidrRouteTable_get_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    u_char* old_string;
    void ( *dataFreeHook )( void* );
    int rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_get_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    for ( ; requests; requests = requests->next ) {
        /*
         * save old pointer, so we can free it if replaced
         */
        old_string = requests->requestvb->value.string;
        dataFreeHook = requests->requestvb->dataFreeHook;
        if ( NULL == requests->requestvb->value.string ) {
            requests->requestvb->value.string = requests->requestvb->buffer;
            requests->requestvb->valueLength = sizeof( requests->requestvb->buffer );
        } else if ( requests->requestvb->buffer == requests->requestvb->value.string ) {
            if ( requests->requestvb->valueLength != sizeof( requests->requestvb->buffer ) )
                requests->requestvb->valueLength = sizeof( requests->requestvb->buffer );
        }

        /*
         * get column data
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetCidrRouteTable_get_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( rc ) {
            if ( MFD_SKIP == rc ) {
                requests->requestvb->type = PRIOT_NOSUCHINSTANCE;
                rc = PRIOT_ERR_NOERROR;
            }
        } else if ( NULL == requests->requestvb->value.string ) {
            Logger_log( LOGGER_PRIORITY_ERR, "NULL varbind data pointer!\n" );
            rc = ErrorCode_GENERR;
        }
        if ( rc )
            Agent_requestSetError( requests, PRIOT_VALIDATE_ERR( rc ) );

        /*
         * if the buffer wasn't used previously for the old data (i.e. it
         * was allcoated memory)  and the get routine replaced the pointer,
         * we need to free the previous pointer.
         */
        if ( old_string && ( old_string != requests->requestvb->buffer ) && ( requests->requestvb->value.string != old_string ) ) {
            if ( dataFreeHook )
                ( *dataFreeHook )( old_string );
            else
                free( old_string );
        }
    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_get_values */

static inline int
_inetCidrRouteTable_check_indexes( inetCidrRouteTable_rowreq_ctx*
        rowreq_ctx )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_check_indexes", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * (INDEX) inetCidrRouteDestType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    /*
     * check that the value is one of defined enums 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_UNKNOWN )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_IPV4 )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_IPV6 )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_IPV4Z )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_IPV6Z )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteDestType != INETADDRESSTYPE_DNS ) ) {
        rc = PRIOT_ERR_WRONGVALUE;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRouteDestType_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /* MORE CHECKING REQUIRED */

    /*
     * (INDEX) inetCidrRouteDest(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    /*
     * check defined range(s). 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( ( rowreq_ctx->tbl_idx.inetCidrRouteDest_len < 0 )
               || ( rowreq_ctx->tbl_idx.inetCidrRouteDest_len > 255 ) ) ) {
        rc = PRIOT_ERR_WRONGLENGTH;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRouteDest_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetCidrRoutePfxLen(3)/InetAddressPrefixLength/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H 
     */
    /*
     * check defined range(s). 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( ( rowreq_ctx->tbl_idx.inetCidrRoutePfxLen < 0 )
               || ( rowreq_ctx->tbl_idx.inetCidrRoutePfxLen > 2040 ) ) ) {
        rc = PRIOT_ERR_WRONGVALUE;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRoutePfxLen_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetCidrRoutePolicy(4)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/a/w/e/r/d/h 
     */
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRoutePolicy_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetCidrRouteNextHopType(5)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
     */
    /*
     * check that the value is one of defined enums 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_UNKNOWN )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_IPV4 )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_IPV6 )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_IPV4Z )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_IPV6Z )
        && ( rowreq_ctx->tbl_idx.inetCidrRouteNextHopType != INETADDRESSTYPE_DNS ) ) {
        rc = PRIOT_ERR_WRONGVALUE;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRouteNextHopType_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * (INDEX) inetCidrRouteNextHop(6)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
     */
    /*
     * check defined range(s). 
     */
    if ( ( ErrorCode_SUCCESS == rc )
        && ( ( rowreq_ctx->tbl_idx.inetCidrRouteNextHop_len < 0 )
               || ( rowreq_ctx->tbl_idx.inetCidrRouteNextHop_len > 255 ) ) ) {
        rc = PRIOT_ERR_WRONGLENGTH;
    }
    if ( MFD_SUCCESS != rc )
        return rc;
    rc = inetCidrRouteNextHop_check_index( rowreq_ctx );
    if ( MFD_SUCCESS != rc )
        return PRIOT_ERR_NOCREATION;

    /*
     * if individual parts look ok, check them as a whole
     */
    return inetCidrRouteTable_validate_index( inetCidrRouteTable_if_ctx.user_ctx, rowreq_ctx );
} /* _inetCidrRouteTable_check_indexes */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*----------------------------------------------------------------------
 *
 * SET: Syntax checks
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check the syntax for a particular column
 */
static inline int
_inetCidrRouteTable_check_column( inetCidrRouteTable_rowreq_ctx*
                                      rowreq_ctx,
    VariableList* var,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_check_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {
    /*
         * (INDEX) inetCidrRouteDestType(1)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTEDESTTYPE:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetCidrRouteDest(2)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
         */
    case COLUMN_INETCIDRROUTEDEST:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetCidrRoutePfxLen(3)/InetAddressPrefixLength/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/H 
         */
    case COLUMN_INETCIDRROUTEPFXLEN:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetCidrRoutePolicy(4)/OBJECTID/ASN_OBJECT_ID/oid(oid)//L/a/w/e/r/d/h 
         */
    case COLUMN_INETCIDRROUTEPOLICY:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetCidrRouteNextHopType(5)/InetAddressType/ASN_INTEGER/long(u_long)//l/a/w/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTENEXTHOPTYPE:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;
    /*
         * (INDEX) inetCidrRouteNextHop(6)/InetAddress/ASN_OCTET_STR/char(char)//L/a/w/e/R/d/h 
         */
    case COLUMN_INETCIDRROUTENEXTHOP:
        rc = PRIOT_ERR_NOTWRITABLE; /* can not change index of active row */
        break;

    /*
         * inetCidrRouteIfIndex(7)/InterfaceIndexOrZero/ASN_INTEGER/long(long)//l/A/W/e/R/d/H 
         */
    case COLUMN_INETCIDRROUTEIFINDEX:
        rc = VariableList_checkType( var, asnINTEGER );
        /*
         * check defined range(s). 
         */
        if ( ( ErrorCode_SUCCESS == rc )
            && ( ( *var->value.integer < 0 )
                   || ( *var->value.integer > 2147483647 ) ) ) {
            rc = PRIOT_ERR_WRONGVALUE;
        }
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteIfIndex", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteIfIndex_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteIfIndex_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTETYPE:
        rc = VariableList_checkType( var, asnINTEGER );
        /*
         * check that the value is one of defined enums 
         */
        if ( ( ErrorCode_SUCCESS == rc )
            && ( *var->value.integer != INETCIDRROUTETYPE_OTHER )
            && ( *var->value.integer != INETCIDRROUTETYPE_REJECT )
            && ( *var->value.integer != INETCIDRROUTETYPE_LOCAL )
            && ( *var->value.integer != INETCIDRROUTETYPE_REMOTE )
            && ( *var->value.integer != INETCIDRROUTETYPE_BLACKHOLE ) ) {
            rc = PRIOT_ERR_WRONGVALUE;
        }
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteType", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteType_check_value( rowreq_ctx,
                *( ( u_long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteType_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteProto(9)/IANAipRouteProtocol/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTEPROTO:
        rc = PRIOT_ERR_NOTWRITABLE;
        break;

    /*
         * inetCidrRouteAge(10)/GAUGE/ASN_GAUGE/u_long(u_long)//l/A/w/e/r/d/h 
         */
    case COLUMN_INETCIDRROUTEAGE:
        rc = PRIOT_ERR_NOTWRITABLE;
        break;

    /*
         * inetCidrRouteNextHopAS(11)/InetAutonomousSystemNumber/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/H 
         */
    case COLUMN_INETCIDRROUTENEXTHOPAS:
        rc = VariableList_checkType( var, asnUNSIGNED );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteNextHopAS", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteNextHopAS_check_value( rowreq_ctx,
                *( ( u_long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteNextHopAS_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteMetric1(12)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC1:
        rc = VariableList_checkType( var, asnINTEGER );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteMetric1", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteMetric1_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteMetric1_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteMetric2(13)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC2:
        rc = VariableList_checkType( var, asnINTEGER );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteMetric2", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteMetric2_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteMetric2_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteMetric3(14)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC3:
        rc = VariableList_checkType( var, asnINTEGER );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteMetric3", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteMetric3_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteMetric3_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteMetric4(15)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC4:
        rc = VariableList_checkType( var, asnINTEGER );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteMetric4", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteMetric4_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteMetric4_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteMetric5(16)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC5:
        rc = VariableList_checkType( var, asnINTEGER );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteMetric5", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteMetric5_check_value( rowreq_ctx,
                *( ( long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteMetric5_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    /*
         * inetCidrRouteStatus(17)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTESTATUS:
        rc = VariableList_checkRowStatusLengthAndRange( var );
        if ( ErrorCode_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:_inetCidrRouteTable_check_column:inetCidrRouteStatus", "varbind validation failed (eg bad type or size)\n" ) );
        } else {
            rc = inetCidrRouteStatus_check_value( rowreq_ctx,
                *( ( u_long* )var->value.string ) );
            if ( ( MFD_SUCCESS != rc ) && ( MFD_NOT_VALID_EVER != rc )
                && ( MFD_NOT_VALID_NOW != rc ) ) {
                Logger_log( LOGGER_PRIORITY_ERR,
                    "bad rc %d from inetCidrRouteStatus_check_value\n",
                    rc );
                rc = ErrorCode_GENERR;
            }
        }
        break;

    default: /** We shouldn't get here */
        rc = ErrorCode_GENERR;
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetCidrRouteTable_check_column\n",
            column );
    }

    return rc;
} /* _inetCidrRouteTable_check_column */

int _mfd_inetCidrRouteTable_check_objects( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    int rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_check_objects", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    for ( ; requests; requests = requests->next ) {

        /*
         * get column number from table request info, and check that column
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetCidrRouteTable_check_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( rc ) {
            Agent_requestSetError( requests, PRIOT_VALIDATE_ERR( rc ) );
            break;
        }

    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_check_objects */

/*----------------------------------------------------------------------
 *
 * SET: check dependencies
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Check dependencies wrapper
 */
static int
_mfd_inetCidrRouteTable_check_dependencies( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_check_dependencies", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetCidrRouteTable_check_dependencies( rowreq_ctx );
    if ( rc ) {
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_check_dependencies\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_check_dependencies */

/*----------------------------------------------------------------------
 *
 * SET: Undo setup
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
static inline int
_inetCidrRouteTable_undo_setup_column( inetCidrRouteTable_rowreq_ctx*
                                           rowreq_ctx,
    int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_undo_setup_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetCidrRouteIfIndex(7)/InterfaceIndexOrZero/ASN_INTEGER/long(long)//l/A/W/e/R/d/H 
         */
    case COLUMN_INETCIDRROUTEIFINDEX:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEIFINDEX_FLAG;
        break;

    /*
         * inetCidrRouteType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTETYPE:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTETYPE_FLAG;
        break;

    /*
         * inetCidrRouteNextHopAS(11)/InetAutonomousSystemNumber/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/H 
         */
    case COLUMN_INETCIDRROUTENEXTHOPAS:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTENEXTHOPAS_FLAG;
        break;

    /*
         * inetCidrRouteMetric1(12)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC1:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC1_FLAG;
        break;

    /*
         * inetCidrRouteMetric2(13)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC2:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC2_FLAG;
        break;

    /*
         * inetCidrRouteMetric3(14)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC3:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC3_FLAG;
        break;

    /*
         * inetCidrRouteMetric4(15)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC4:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC4_FLAG;
        break;

    /*
         * inetCidrRouteMetric5(16)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC5:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC5_FLAG;
        break;

    /*
         * inetCidrRouteStatus(17)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTESTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTESTATUS_FLAG;
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetCidrRouteTable_undo_setup_column\n",
            column );
        break;
    }

    return rc;
} /* _inetCidrRouteTable_undo_setup_column */

/**
 * @internal
 * undo setup
 */
int _mfd_inetCidrRouteTable_undo_setup( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_undo_setup", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * allocate undo context
     */
    rowreq_ctx->undo = inetCidrRouteTable_allocate_data();
    if ( NULL == rowreq_ctx->undo ) {
        /** msg already logged */
        Agent_requestSetErrorAll( requests,
            PRIOT_ERR_RESOURCEUNAVAILABLE );
        return PRIOT_ERR_NOERROR;
    }

    /*
     * row undo setup
     */
    rowreq_ctx->column_set_flags = 0;
    rc = inetCidrRouteTable_undo_setup( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_undo_setup\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    } else {
        /*
         * column undo setup
         */
        TableRequestInfo* tri;
        for ( ; requests; requests = requests->next ) {
            /*
             * set column data
             */
            tri = Table_extractTableInfo( requests );
            if ( NULL == tri )
                continue;

            rc = _inetCidrRouteTable_undo_setup_column( rowreq_ctx,
                tri->colnum );
            if ( MFD_SUCCESS != rc ) {
                DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                         "inetCidrRouteTable_undo_setup_column\n",
                    rc ) );
                Agent_setRequestError( agtreq_info, requests,
                    PRIOT_VALIDATE_ERR( rc ) );
            }
        } /* for results */
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_undo_setup */

/**
 * @internal
 * undo setup
 */
int _mfd_inetCidrRouteTable_undo_cleanup( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    int rc;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_undo_cleanup", "called\n" ) );

    /*
     * failed row create in early stages has no rowreq_ctx
     */
    if ( NULL == rowreq_ctx )
        return MFD_SUCCESS;

    /*
     * call user cleanup
     */
    rc = inetCidrRouteTable_undo_cleanup( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_undo_cleanup\n",
            rc ) );
    }

    /*
     * release undo context, if needed
     */
    if ( rowreq_ctx->undo ) {
        inetCidrRouteTable_release_data( rowreq_ctx->undo );
        rowreq_ctx->undo = NULL;
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_undo_cleanup */

/*----------------------------------------------------------------------
 *
 * SET: Set values
 *
 *---------------------------------------------------------------------*/
/*
 * @internal
 * Set the value for a particular column
 */
static inline int
_inetCidrRouteTable_set_column( inetCidrRouteTable_rowreq_ctx* rowreq_ctx,
    VariableList* var, int column )
{
    int rc = ErrorCode_SUCCESS;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_set_column", "called for %d\n", column ) );

    Assert_assert( NULL != rowreq_ctx );

    switch ( column ) {

    /*
         * inetCidrRouteIfIndex(7)/InterfaceIndexOrZero/ASN_INTEGER/long(long)//l/A/W/e/R/d/H 
         */
    case COLUMN_INETCIDRROUTEIFINDEX:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEIFINDEX_FLAG;
        rc = inetCidrRouteIfIndex_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteType(8)/INTEGER/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTETYPE:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTETYPE_FLAG;
        rc = inetCidrRouteType_set( rowreq_ctx,
            *( ( u_long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteNextHopAS(11)/InetAutonomousSystemNumber/ASN_UNSIGNED/u_long(u_long)//l/A/W/e/r/D/H 
         */
    case COLUMN_INETCIDRROUTENEXTHOPAS:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTENEXTHOPAS_FLAG;
        rc = inetCidrRouteNextHopAS_set( rowreq_ctx,
            *( ( u_long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteMetric1(12)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC1:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC1_FLAG;
        rc = inetCidrRouteMetric1_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteMetric2(13)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC2:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC2_FLAG;
        rc = inetCidrRouteMetric2_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteMetric3(14)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC3:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC3_FLAG;
        rc = inetCidrRouteMetric3_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteMetric4(15)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC4:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC4_FLAG;
        rc = inetCidrRouteMetric4_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteMetric5(16)/INTEGER32/ASN_INTEGER/long(long)//l/A/W/e/r/D/h 
         */
    case COLUMN_INETCIDRROUTEMETRIC5:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTEMETRIC5_FLAG;
        rc = inetCidrRouteMetric5_set( rowreq_ctx,
            *( ( long* )var->value.string ) );
        break;

    /*
         * inetCidrRouteStatus(17)/RowStatus/ASN_INTEGER/long(u_long)//l/A/W/E/r/d/h 
         */
    case COLUMN_INETCIDRROUTESTATUS:
        rowreq_ctx->column_set_flags |= COLUMN_INETCIDRROUTESTATUS_FLAG;
        rc = inetCidrRouteStatus_set( rowreq_ctx,
            *( ( u_long* )var->value.string ) );
        break;

    default:
        Logger_log( LOGGER_PRIORITY_ERR,
            "unknown column %d in _inetCidrRouteTable_set_column\n",
            column );
        rc = ErrorCode_GENERR;
        break;
    }

    return rc;
} /* _inetCidrRouteTable_set_column */

int _mfd_inetCidrRouteTable_set_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );
    TableRequestInfo* tri;
    int rc = PRIOT_ERR_NOERROR;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_set_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rowreq_ctx->column_set_flags = 0;
    for ( ; requests; requests = requests->next ) {
        /*
         * set column data
         */
        tri = Table_extractTableInfo( requests );
        if ( NULL == tri )
            continue;

        rc = _inetCidrRouteTable_set_column( rowreq_ctx,
            requests->requestvb,
            tri->colnum );
        if ( MFD_SUCCESS != rc ) {
            DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                     "inetCidrRouteTable_set_column\n",
                rc ) );
            Agent_setRequestError( agtreq_info, requests,
                PRIOT_VALIDATE_ERR( rc ) );
        }
    } /* for results */

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_set_values */

/*----------------------------------------------------------------------
 *
 * SET: commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit the values
 */
int _mfd_inetCidrRouteTable_commit( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetCidrRouteTable_commit( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_commit\n",
            rc ) );
        Agent_requestSetErrorAll( requests, PRIOT_VALIDATE_ERR( rc ) );
    }

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        /*
         * if we successfully commited this row, set the dirty flag. Use the
         * current value + 1 (i.e. dirty = # rows changed).
         * this is checked in post_request...
         */
        inetCidrRouteTable_dirty_set( inetCidrRouteTable_dirty_get() + 1 ); /* set table dirty flag */
    }

    return PRIOT_ERR_NOERROR;
}

int _mfd_inetCidrRouteTable_undo_commit( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_undo_commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        u_int d = inetCidrRouteTable_dirty_get();

        Assert_assert( d != 0 );
        if ( d )
            inetCidrRouteTable_dirty_set( d - 1 );
    }

    rc = inetCidrRouteTable_undo_commit( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_undo_commit\n",
            rc ) );
    }

    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DIRTY ) {
        Logger_log( LOGGER_PRIORITY_WARNING,
            "inetCidrRouteTable row dirty flag still set after undo_commit\n" );
        rowreq_ctx->rowreq_flags &= ~MFD_ROW_DIRTY;
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_commit */

/*----------------------------------------------------------------------
 *
 * SET: Undo
 *
 *---------------------------------------------------------------------*/
int _mfd_inetCidrRouteTable_undo_values( MibHandler* handler,
    HandlerRegistration* reginfo,
    AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    int rc;
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_undo_values", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    rc = inetCidrRouteTable_undo( rowreq_ctx );
    if ( MFD_SUCCESS != rc ) {
        /*
         * nothing we can do about it but log it
         */
        DEBUG_MSGTL( ( "inetCidrRouteTable:mfd", "error %d from "
                                                 "inetCidrRouteTable_undo\n",
            rc ) );
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_undo_values */

/*----------------------------------------------------------------------
 *
 * SET: irreversible commit
 *
 *---------------------------------------------------------------------*/
/**
 * @internal
 * commit irreversible actions
 */
int _mfd_inetCidrRouteTable_irreversible_commit( MibHandler* handler, HandlerRegistration* reginfo, AgentRequestInfo* agtreq_info,
    RequestInfo* requests )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        TableContainer_rowExtract( requests );

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_mfd_inetCidrRouteTable_irreversible:commit", "called\n" ) );

    Assert_assert( NULL != rowreq_ctx );

    /*
     * check for and handle row creation/deletion
     * and update column exist flags...
     */
    if ( rowreq_ctx->rowreq_flags & MFD_ROW_DELETED ) {
        if ( !( rowreq_ctx->rowreq_flags & MFD_ROW_CREATED ) )
            CONTAINER_REMOVE( inetCidrRouteTable_if_ctx.container, rowreq_ctx );
    } else {
        if ( rowreq_ctx->column_set_flags ) {
            rowreq_ctx->column_set_flags = 0;
        }
        if ( rowreq_ctx->rowreq_flags & MFD_ROW_CREATED ) {
            rowreq_ctx->rowreq_flags &= ~MFD_ROW_CREATED;
            CONTAINER_INSERT( inetCidrRouteTable_if_ctx.container,
                rowreq_ctx );
        }
    }

    return PRIOT_ERR_NOERROR;
} /* _mfd_inetCidrRouteTable_irreversible_commit */

/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
static void _container_free( Container_Container* container );

/**
 * @internal
 */
static int
_cache_load( Cache* cache, void* vmagic )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_cache_load", "called\n" ) );

    if ( ( NULL == cache ) || ( NULL == cache->magic ) ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid cache for inetCidrRouteTable_cache_load\n" );
        return -1;
    }

    /** should only be called for an invalid or expired cache */
    Assert_assert( ( 0 == cache->valid ) || ( 1 == cache->expired ) );

    /*
     * call user code
     */
    return inetCidrRouteTable_container_load( ( Container_Container* )cache->magic );
} /* _cache_load */

/**
 * @internal
 */
static void
_cache_free( Cache* cache, void* magic )
{
    Container_Container* container;

    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_cache_free", "called\n" ) );

    if ( ( NULL == cache ) || ( NULL == cache->magic ) ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid cache in inetCidrRouteTable_cache_free\n" );
        return;
    }

    container = ( Container_Container* )cache->magic;

    _container_free( container );
} /* _cache_free */

/**
 * @internal
 */
static void
_container_item_free( inetCidrRouteTable_rowreq_ctx* rowreq_ctx,
    void* context )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_container_item_free",
        "called\n" ) );

    if ( NULL == rowreq_ctx )
        return;

    inetCidrRouteTable_release_rowreq_ctx( rowreq_ctx );
} /* _container_item_free */

/**
 * @internal
 */
static void
_container_free( Container_Container* container )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_container_free",
        "called\n" ) );

    if ( NULL == container ) {
        Logger_log( LOGGER_PRIORITY_ERR,
            "invalid container in inetCidrRouteTable_container_free\n" );
        return;
    }

    /*
     * call user code
     */
    inetCidrRouteTable_container_free( container );

    /*
     * free all items. inefficient, but easy.
     */
    CONTAINER_CLEAR( container,
        ( Container_FuncObjFunc* )_container_item_free,
        NULL );
} /* _container_free */

/**
 * @internal
 * initialize the container with functions or wrappers
 */
void _inetCidrRouteTable_container_init( inetCidrRouteTable_interface_ctx*
        if_ctx )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_container_init", "called\n" ) );

    /*
     * cache init
     */
    if_ctx->cache = CacheHandler_create( INETCIDRROUTETABLE_CACHE_TIMEOUT,
        _cache_load, _cache_free,
        inetCidrRouteTable_oid,
        inetCidrRouteTable_oid_size );

    if ( NULL == if_ctx->cache ) {
        Logger_log( LOGGER_PRIORITY_ERR, "error creating cache for ipCidrRouteTable\n" );
        return;
    }

    if_ctx->cache->flags = CacheOperation_DONT_INVALIDATE_ON_SET;

    inetCidrRouteTable_container_init( &if_ctx->container, if_ctx->cache );
    if ( NULL == if_ctx->container ) {
        if_ctx->container = Container_find( "inetCidrRouteTable:tableContainer" );
        if ( NULL == if_ctx->container ) {
            Logger_log( LOGGER_PRIORITY_ERR, "error creating container in "
                                             "inetCidrRouteTable_container_init\n" );
            return;
        }
    }

    if_ctx->container->containerName = strdup( "inetCidrRouteTable" );

    /* set allow duplicates this makes insert O(1) */
    ContainerBinaryArray_optionsSet( if_ctx->container, 1,
        CONTAINER_KEY_ALLOW_DUPLICATES );

    if ( NULL != if_ctx->cache )
        if_ctx->cache->magic = ( void* )if_ctx->container;
} /* _inetCidrRouteTable_container_init */

/**
 * @internal
 * shutdown the container with functions or wrappers
 */
void _inetCidrRouteTable_container_shutdown( inetCidrRouteTable_interface_ctx*
        if_ctx )
{
    DEBUG_MSGTL( ( "internal:inetCidrRouteTable:_inetCidrRouteTable_container_shutdown", "called\n" ) );

    inetCidrRouteTable_container_shutdown( if_ctx->container );

    _container_free( if_ctx->container );

} /* _inetCidrRouteTable_container_shutdown */

inetCidrRouteTable_rowreq_ctx*
inetCidrRouteTable_row_find_by_mib_index( inetCidrRouteTable_mib_index*
        mib_idx )
{
    inetCidrRouteTable_rowreq_ctx* rowreq_ctx;
    oid oid_tmp[ asnMAX_OID_LEN ];
    Types_Index oid_idx;
    int rc;

    /*
     * set up storage for OID
     */
    oid_idx.oids = oid_tmp;
    oid_idx.len = sizeof( oid_tmp ) / sizeof( oid );

    /*
     * convert
     */
    rc = inetCidrRouteTable_index_to_oid( &oid_idx, mib_idx );
    if ( MFD_SUCCESS != rc )
        return NULL;

    rowreq_ctx = ( inetCidrRouteTable_rowreq_ctx* )
        CONTAINER_FIND( inetCidrRouteTable_if_ctx.container, &oid_idx );

    return rowreq_ctx;
}
